// Code generated by 'yaegi extract git.golaxy.org/core/extension'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/core/extension"
	"git.golaxy.org/core/utils/generic"
	"git.golaxy.org/core/utils/iface"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/core/extension/extension"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ErrExtension":         reflect.ValueOf(&extension.ErrExtension).Elem(),
		"NewPluginBundle":      reflect.ValueOf(extension.NewPluginBundle),
		"PluginState_Active":   reflect.ValueOf(extension.PluginState_Active),
		"PluginState_Inactive": reflect.ValueOf(extension.PluginState_Inactive),
		"PluginState_Loaded":   reflect.ValueOf(extension.PluginState_Loaded),
		"Uninstall":            reflect.ValueOf(extension.Uninstall),
		"UnsafePluginBundle":   reflect.ValueOf(extension.UnsafePluginBundle),
		"UnsafePluginStatus":   reflect.ValueOf(extension.UnsafePluginStatus),

		// type definitions
		"PluginBundle":   reflect.ValueOf((*extension.PluginBundle)(nil)),
		"PluginProvider": reflect.ValueOf((*extension.PluginProvider)(nil)),
		"PluginState":    reflect.ValueOf((*extension.PluginState)(nil)),
		"PluginStatus":   reflect.ValueOf((*extension.PluginStatus)(nil)),

		// interface wrapper definitions
		"_PluginBundle":   reflect.ValueOf((*_git_golaxy_org_core_extension_PluginBundle)(nil)),
		"_PluginProvider": reflect.ValueOf((*_git_golaxy_org_core_extension_PluginProvider)(nil)),
		"_PluginStatus":   reflect.ValueOf((*_git_golaxy_org_core_extension_PluginStatus)(nil)),
	}
}

// _git_golaxy_org_core_extension_PluginBundle is an interface wrapper for PluginBundle type
type _git_golaxy_org_core_extension_PluginBundle struct {
	IValue           interface{}
	WGet             func(name string) (extension.PluginStatus, bool)
	WGetPluginBundle func() extension.PluginBundle
	WInstall         func(pluginFace iface.FaceAny, name ...string)
	WRange           func(fun generic.Func1[extension.PluginStatus, bool])
	WReversedRange   func(fun generic.Func1[extension.PluginStatus, bool])
	WUninstall       func(name string)
}

func (W _git_golaxy_org_core_extension_PluginBundle) Get(name string) (extension.PluginStatus, bool) {
	return W.WGet(name)
}
func (W _git_golaxy_org_core_extension_PluginBundle) GetPluginBundle() extension.PluginBundle {
	return W.WGetPluginBundle()
}
func (W _git_golaxy_org_core_extension_PluginBundle) Install(pluginFace iface.FaceAny, name ...string) {
	W.WInstall(pluginFace, name...)
}
func (W _git_golaxy_org_core_extension_PluginBundle) Range(fun generic.Func1[extension.PluginStatus, bool]) {
	W.WRange(fun)
}
func (W _git_golaxy_org_core_extension_PluginBundle) ReversedRange(fun generic.Func1[extension.PluginStatus, bool]) {
	W.WReversedRange(fun)
}
func (W _git_golaxy_org_core_extension_PluginBundle) Uninstall(name string) { W.WUninstall(name) }

// _git_golaxy_org_core_extension_PluginProvider is an interface wrapper for PluginProvider type
type _git_golaxy_org_core_extension_PluginProvider struct {
	IValue           interface{}
	WGetPluginBundle func() extension.PluginBundle
}

func (W _git_golaxy_org_core_extension_PluginProvider) GetPluginBundle() extension.PluginBundle {
	return W.WGetPluginBundle()
}

// _git_golaxy_org_core_extension_PluginStatus is an interface wrapper for PluginStatus type
type _git_golaxy_org_core_extension_PluginStatus struct {
	IValue        interface{}
	WInstanceFace func() iface.FaceAny
	WName         func() string
	WReflected    func() reflect.Value
	WState        func() extension.PluginState
}

func (W _git_golaxy_org_core_extension_PluginStatus) InstanceFace() iface.FaceAny {
	return W.WInstanceFace()
}
func (W _git_golaxy_org_core_extension_PluginStatus) Name() string                 { return W.WName() }
func (W _git_golaxy_org_core_extension_PluginStatus) Reflected() reflect.Value     { return W.WReflected() }
func (W _git_golaxy_org_core_extension_PluginStatus) State() extension.PluginState { return W.WState() }
