/*
 * This file is part of Golaxy Distributed Service Development Framework.
 *
 * Golaxy Distributed Service Development Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * Golaxy Distributed Service Development Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Golaxy Distributed Service Development Framework. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2024 pangdogs.
 */

package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"git.golaxy.org/core/utils/generic"
	"github.com/spf13/viper"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/reflect/protoregistry"
)

func genGoCode(outDir string) {
	extensions, err := parseExtensions(protoregistry.GlobalTypes)
	if err != nil {
		log.Panicf("parse proto file failed, %s", err)
	}

	var msgDecls generic.SliceMap[string, protoreflect.MessageType]

	protoregistry.GlobalTypes.RangeMessages(func(msg protoreflect.MessageType) bool {
		isTable := proto.GetExtension(msg.Descriptor().Options(), extensions.IsTable).(bool)
		if !isTable {
			return true
		}
		msgDecls.Add(string(msg.Descriptor().Name()), msg)
		return true
	})

	const tmpl = `{{.Comment}}

package {{.Package}}

import (
	"git.golaxy.org/scaffold/tools/excelc/excelutils"
	"path/filepath"
)

type Tables struct {
	{{- range .Tables}}
	{{.K}} *{{.K}}
	{{- end}}
}

func LoadBinaryFiles(dir string) (*Tables, error) {
	tabs := &Tables{}
	{{- range .Tables}}
	tabs.{{.K}} = &{{.K}}{}
	if err := excelutils.LoadTableFromBinaryFile(tabs.{{.K}}, filepath.Join(dir, "{{.K}}.bin")); err != nil {
		return nil, err
	}
	{{- end}}
	return tabs, nil
}

func LoadJsonFiles(dir string) (*Tables, error) {
	tabs := &Tables{}
	{{- range .Tables}}
	tabs.{{.K}} = &{{.K}}{}
	if err := excelutils.LoadTableFromJsonFile(tabs.{{.K}}, filepath.Join(dir, "{{.K}}.json")); err != nil {
		return nil, err
	}
	{{- end}}
	return tabs, nil
}
`

	type TmplArgs struct {
		Comment string
		Package string
		Tables  generic.SliceMap[string, protoreflect.MessageType]
	}

	args := TmplArgs{
		Comment: fmt.Sprintf(`// Code generated by %[1]s; DO NOT EDIT.
// Command: %[1]s %[2]s
// Note: This file is auto-generated. DO NOT EDIT THIS FILE DIRECTLY.`, strings.TrimSuffix(filepath.Base(os.Args[0]), filepath.Ext(os.Args[0])), strings.Join(os.Args[1:], " ")),
		Package: viper.GetString("pb_package"),
		Tables:  msgDecls,
	}

	outFilePath, _ := filepath.Abs(filepath.Join(outDir, "tables.go"))

	t := template.Must(template.New("code").Parse(tmpl))

	os.MkdirAll(outDir, os.ModePerm)

	file, err := os.OpenFile(outFilePath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, os.ModePerm)
	if err != nil {
		log.Panic(err)
	}
	defer file.Close()

	err = t.Execute(file, args)
	if err != nil {
		log.Panic(err)
	}
}
