/*
 * This file is part of Golaxy Distributed Service Development Framework.
 *
 * Golaxy Distributed Service Development Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * Golaxy Distributed Service Development Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Golaxy Distributed Service Development Framework. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2024 pangdogs.
 */

package main

import (
	"log"
	"os"
	"path/filepath"
	"unicode"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

func main() {
	cmd := &cobra.Command{
		Short: "Excel table processing tool for generating schema code and exporting data files.",
		Run: func(cmd *cobra.Command, args []string) {
			cmd.Help()
		},
		CompletionOptions: cobra.CompletionOptions{
			DisableDefaultCmd: true,
		},
	}

	protoCmd := &cobra.Command{
		Use:   "proto",
		Short: "Generate excel schema proto files.",
		PreRun: func(cmd *cobra.Command, args []string) {
			viper.BindPFlags(cmd.Flags())

			{
				excelFilePaths := viper.GetStringSlice("excel_files")

				for _, path := range excelFilePaths {
					if filepath.Ext(path) != ".xlsx" {
						log.Panicf("[--excel_files] file %q is invalid: file extension must be .xlsx", path)
					}
					if !unicode.IsLetter(rune(filepath.Base(path)[0])) {
						log.Panicf("[--excel_files] file %q is invalid: the first character of the file name must be a letter", path)
					}
					stat, err := os.Stat(path)
					if err != nil {
						log.Panicf("[--excel_files] file %q is invalid: %s", path, err)
					}
					if stat.IsDir() {
						log.Panicf("[--excel_files] file %q is invalid: directories are not allowed", path)
					}
				}
			}

			{
				excelDir := viper.GetString("excel_dir")
				if excelDir != "" {
					stat, err := os.Stat(excelDir)
					if err != nil {
						log.Panicf("[--excel_dir] directory is invalid: %s", err)
					}
					if !stat.IsDir() {
						log.Panic("[--excel_dir] path must be a directory")
					}
				}
			}

			{
				pkg := viper.GetString("pb_package")
				if pkg == "" {
					log.Panic("[--pb_package] value cannot be empty")
				}
			}

			{
				uniqueIndexAs := viper.GetString("pb_unique_index_as")
				switch uniqueIndexAs {
				case "hash_unique_index", "sorted_unique_index":
					break
				default:
					log.Panicf("[--pb_unique_index_as] value must be hash_unique_index or sorted_unique_index, but got %q", uniqueIndexAs)
				}
			}
		},
		Run: cmdGenProto,
	}
	protoCmd.Flags().StringSlice("excel_files", nil, "Specify the input excel file list (preferred).")
	protoCmd.Flags().String("excel_dir", "", "Specify the input excel file directory.")
	protoCmd.Flags().String("pb_out", "", "Specify the output proto file directory.")
	protoCmd.Flags().String("pb_package", "excel", "Specify the output proto package name.")
	protoCmd.Flags().StringSlice("pb_imports", nil, "Specify output proto imports.")
	protoCmd.Flags().Int("pb_custom_options", 10000, "Specify the custom proto option base number.")
	protoCmd.Flags().StringToString("pb_options", map[string]string{"go_package": "./excel"}, "Specify output proto file options.")
	protoCmd.Flags().String("pb_unique_index_as", "hash_unique_index", "Specify how `unique_index` is emitted in proto file (hash_unique_index/sorted_unique_index).")
	protoCmd.Flags().StringSlice("targets", nil, "Specify output target platforms and control access by platform.")

	codeCmd := &cobra.Command{
		Use:   "code",
		Short: "Generate excel data access code.",
		PreRun: func(cmd *cobra.Command, args []string) {
			viper.BindPFlags(cmd.Flags())

			{
				pbDir := viper.GetString("pb_dir")
				if pbDir == "" {
					log.Panic("[--pb_dir] value cannot be empty")
				}
				stat, err := os.Stat(pbDir)
				if err != nil {
					log.Panicf("[--pb_dir] directory is invalid: %s", err)
				}
				if !stat.IsDir() {
					log.Panic("[--pb_dir] path must be a directory")
				}
			}

			{
				pkg := viper.GetString("pb_package")
				if pkg == "" {
					log.Panic("[--pb_package] value cannot be empty")
				}
			}
		},
		Run: cmdGenCode,
	}
	codeCmd.Flags().String("pb_dir", "", "Specify the directory of proto files generated by excel compilation.")
	codeCmd.Flags().String("pb_package", "excel", "Specify the proto package name generated by excel compilation.")
	codeCmd.Flags().String("go_out", "", "Output directory for Go code.")
	codeCmd.Flags().String("gdscript_out", "", "Output directory for GDScript code.")
	codeCmd.Flags().String("gdscript_default_load_data_dir", "res://res/excel/", "Default data loading directory in generated GDScript code.")

	dataCmd := &cobra.Command{
		Use:   "data",
		Short: "Export excel data.",
		PreRun: func(cmd *cobra.Command, args []string) {
			viper.BindPFlags(cmd.Flags())

			{
				excelFilePaths := viper.GetStringSlice("excel_files")

				for _, path := range excelFilePaths {
					if filepath.Ext(path) != ".xlsx" {
						log.Panicf("[--excel_files] file %q is invalid: file extension must be .xlsx", path)
					}
					if !unicode.IsLetter(rune(filepath.Base(path)[0])) {
						log.Panicf("[--excel_files] file %q is invalid: the first character of the file name must be a letter", path)
					}
					stat, err := os.Stat(path)
					if err != nil {
						log.Panicf("[--excel_files] file %q is invalid: %s", path, err)
					}
					if stat.IsDir() {
						log.Panicf("[--excel_files] file %q is invalid: directories are not allowed", path)
					}
				}
			}

			{
				excelDir := viper.GetString("excel_dir")
				if excelDir != "" {
					stat, err := os.Stat(excelDir)
					if err != nil {
						log.Panicf("[--excel_dir] directory is invalid: %s", err)
					}
					if !stat.IsDir() {
						log.Panic("[--excel_dir] path must be a directory")
					}
				}
			}

			{
				pbDir := viper.GetString("pb_dir")
				if pbDir == "" {
					log.Panic("[--pb_dir] value cannot be empty")
				}
				stat, err := os.Stat(pbDir)
				if err != nil {
					log.Panicf("[--pb_dir] directory is invalid: %s", err)
				}
				if !stat.IsDir() {
					log.Panic("[--pb_dir] path must be a directory")
				}
			}

			{
				pkg := viper.GetString("pb_package")
				if pkg == "" {
					log.Panic("[--pb_package] value cannot be empty")
				}
			}
		},
		Run: cmdGenData,
	}
	dataCmd.Flags().StringSlice("excel_files", nil, "Specify the input excel file list (preferred).")
	dataCmd.Flags().String("excel_dir", "", "Specify the input excel file directory.")
	dataCmd.Flags().String("pb_dir", "", "Specify the directory of proto files generated by excel compilation.")
	dataCmd.Flags().String("pb_package", "excel", "Specify the proto package name generated by excel compilation.")
	dataCmd.Flags().StringSlice("targets", nil, "Specify output target platforms and control access by platform.")
	dataCmd.Flags().String("binary_out", "", "Output directory for binary data.")
	dataCmd.Flags().String("json_out", "", "Output directory for JSON data.")
	dataCmd.Flags().Bool("json_multiline", false, "Whether JSON data should be multiline.")
	dataCmd.Flags().String("json_indent", "", "Indent string for JSON data.")

	cmd.AddCommand(protoCmd, codeCmd, dataCmd)

	if err := cmd.Execute(); err != nil {
		log.Panic(err)
	}
}
