/*
 * This file is part of Golaxy Distributed Service Development Framework.
 *
 * Golaxy Distributed Service Development Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * Golaxy Distributed Service Development Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Golaxy Distributed Service Development Framework. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2024 pangdogs.
 */

package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"git.golaxy.org/core/utils/generic"
	"github.com/elliotchance/pie/v2"
	"github.com/spf13/viper"
	"github.com/xuri/excelize/v2"
)

const (
	DependencyProto = "excelc"
)

func genDependencyProtoFile(outDir string) {
	const tmpl = `{{.Comment}}
syntax = 'proto3';

// package
package {{.Package}};

// imports
import "google/protobuf/descriptor.proto";

// options
{{- range .Options}}
{{.}}
{{- end}}

message SortedUniqueIndex {
	repeated uint64 Values = 1;
	repeated uint32 Offsets = 2;
}

message IndexConflict {
	repeated uint32 Offsets = 1;
}

message IndexType {
	enum Enum {
		None = 0;
		HashUniqueIndex = 1;
		SortedUniqueIndex = 2;
	}
}

message Chunk {
	uint32 Offset = 1;
	uint32 Count = 2;
}

message ChunkManifest {
	uint32 ChunkSize = 1;
	repeated Chunk Chunks = 2;
}

extend google.protobuf.MessageOptions {
	optional bool IsColumns = {{Add .CustomOptions 101}};
	optional bool IsTable = {{Add .CustomOptions 102}};
	optional bool IsEnum = {{Add .CustomOptions 103}};
}

extend google.protobuf.FieldOptions {
	optional string Separator = {{Add .CustomOptions 201}};
	optional string FieldAlias = {{Add .CustomOptions 202}};
	repeated string Scope = {{Add .CustomOptions 203}};
	optional IndexType.Enum IndexType_ = {{Add .CustomOptions 204}};
	optional string IndexFields = {{Add .CustomOptions 205}};
	repeated int32 HashUniqueIndex = {{Add .CustomOptions 206}};
	repeated int32 SortedUniqueIndex_ = {{Add .CustomOptions 207}};
}

extend google.protobuf.EnumValueOptions {
	optional string EnumValueAlias = {{Add .CustomOptions 301}};
}
`

	type TmplArgs struct {
		Comment       string
		Package       string
		Options       []string
		CustomOptions int
	}

	args := TmplArgs{
		Comment: fmt.Sprintf(`// Proto definition generated by %[1]s.
// Command: %[1]s %[2]s
// Note: This file is auto-generated. DO NOT EDIT THIS FILE DIRECTLY.`, strings.TrimSuffix(filepath.Base(os.Args[0]), filepath.Ext(os.Args[0])), strings.Join(os.Args[1:], " ")),
		Package:       viper.GetString("pb_package"),
		CustomOptions: viper.GetInt("pb_custom_options"),
	}

	for k, v := range viper.GetStringMapString("pb_options") {
		args.Options = append(args.Options, fmt.Sprintf("option %s='%s';", k, v))
	}
	sort.Strings(args.Options)

	outFilePath, _ := filepath.Abs(filepath.Join(outDir, fmt.Sprintf("%s.proto", DependencyProto)))

	t := template.Must(template.New("proto").
		Funcs(template.FuncMap{
			"Add": func(n ...int) int { return pie.Sum(n) },
		}).
		Parse(tmpl))

	os.MkdirAll(outDir, os.ModePerm)

	outFile, err := os.OpenFile(outFilePath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, os.ModePerm)
	if err != nil {
		log.Panic(err)
	}
	defer outFile.Close()

	err = t.Execute(outFile, args)
	if err != nil {
		log.Panic(err)
	}
}

func predeclareProtoFile(file *excelize.File, globalDecls *generic.SliceMap[Type, *Decl]) {
	typeDecls := predeclareTypeDecls(file)

	typeDecls.Each(func(ty Type, decl *Decl) {
		if !globalDecls.TryAdd(ty, decl) {
			log.Panicf("read excel file %q failed: duplicate type definition %q", file.Path, ty)
		}
	})

	columnDecls := predeclareTableDecls(file)

	columnDecls.Each(func(ty Type, decl *Decl) {
		if !globalDecls.TryAdd(ty, decl) {
			log.Panicf("read excel file %q failed: duplicate type definition %q", file.Path, ty)
		}
	})
}

func genProtoFile(file *excelize.File, globalDecls *generic.SliceMap[Type, *Decl], outDir string) {
	typeDecls := parseTypeDecls(file, globalDecls)
	columnDecls := parseTableDecls(file, globalDecls)

	if typeDecls.Len() <= 0 && columnDecls.Len() <= 0 {
		return
	}

	typeDecls.Each(func(_ Type, decl *Decl) {
		if err := decl.CheckPbNumbers(); err != nil {
			log.Panicf("read excel file %q failed: %s", file.Path, err)
		}
	})
	columnDecls.Each(func(_ Type, decl *Decl) {
		if err := decl.CheckPbNumbers(); err != nil {
			log.Panicf("read excel file %q failed: %s", file.Path, err)
		}
	})

	const tmpl = `{{.Comment}}
syntax = 'proto3';

// package
package {{.Package}};
{{- $package := .Package}}

// imports
{{- range .Imports}}
{{.}}
{{- end}}

// options
{{- range .Options}}
{{.}}
{{- end}}

// enums
{{- range .Enums}}
message {{.Type}} {
	option ({{$package}}.IsEnum) = true;
	enum Enum {
		{{- range .EnumFields}}
		{{.K}} = {{.V.EnumValue}}{{- .V.ProtobufMeta -}}; // {{.V.Alias}} - {{.V.Comment}}
		{{- end}}
	}
}
{{end}}

// structs
{{- range .Structs}}
message {{.Type}} {
	{{- range $i, $kv := .StructFields}}
	{{$kv.V.ProtoType}} {{$kv.K}} = {{$kv.V.Number}}{{- $kv.V.ProtobufMeta -}}; // {{.V.Alias}} - {{.V.Comment}}
	{{- end}}
}
{{end}}

// table and columns
{{- range .Columns}}
message {{.ProtoType}} {
	option ({{$package}}.IsColumns) = true;
	{{- range $i, $kv := .StructFields}}
	{{$kv.V.ProtoType}} {{$kv.K}} = {{$kv.V.Number}}{{- $kv.V.ProtobufMeta -}}; // {{.V.Alias}} - {{.V.Comment}}
	{{- end}}
}

message {{TableName .ProtoType}} {
	option ({{$package}}.IsTable) = true;
	repeated {{.ProtoType}} Rows = 1;
	{{- $StructHashUniqueIndexesCount := .StructHashUniqueIndexes.Len -}}
	{{- $StructSortedUniqueIndexesCount := .StructSortedUniqueIndexes.Len -}}
	{{- range $i, $kv := .StructHashUniqueIndexes}}
	map<uint64, uint32> HashUniqueIndex{{$kv.K}} = {{Add $i 2}} [({{$package}}.IndexType_) = HashUniqueIndex, ({{$package}}.IndexFields) = '{{$kv.V}}']; 
	{{- end}}
	{{- range $i, $kv := .StructHashUniqueIndexes}}
	map<uint64, IndexConflict> HashUniqueIndex{{$kv.K}}Conflict = {{Add $i 2 $StructHashUniqueIndexesCount}};
	{{- end}}
	{{- range $i, $kv := .StructSortedUniqueIndexes}}
	SortedUniqueIndex SortedUniqueIndex{{$kv.K}} = {{Add $i 2 $StructHashUniqueIndexesCount $StructHashUniqueIndexesCount}} [({{$package}}.IndexType_) = SortedUniqueIndex, ({{$package}}.IndexFields) = '{{$kv.V}}'];
	{{- end}}
	{{- range $i, $kv := .StructSortedUniqueIndexes}}
	map<uint64, IndexConflict> SortedUniqueIndex{{$kv.K}}Conflict = {{Add $i 2 $StructHashUniqueIndexesCount $StructHashUniqueIndexesCount $StructSortedUniqueIndexesCount}};
	{{- end}}
	ChunkManifest ChunkManifest = {{Add 2 $StructHashUniqueIndexesCount $StructHashUniqueIndexesCount $StructSortedUniqueIndexesCount $StructSortedUniqueIndexesCount}}; 
}
{{end}}
`

	type TmplArgs struct {
		Comment string
		Package string
		Imports []string
		Options []string
		Enums   []*Decl
		Structs []*Decl
		Columns []*Decl
	}

	args := TmplArgs{
		Comment: fmt.Sprintf(`// Proto definition generated by %[1]s.
// Command: %[1]s %[2]s
// Excel File: %[3]s
// Note: This file is auto-generated. DO NOT EDIT THIS FILE DIRECTLY.`, strings.TrimSuffix(filepath.Base(os.Args[0]), filepath.Ext(os.Args[0])), strings.Join(os.Args[1:], " "), file.Path),
		Package: viper.GetString("pb_package"),
	}
	importSet := map[string]struct{}{}
	addImport := func(imp string) {
		if _, ok := importSet[imp]; ok {
			return
		}
		importSet[imp] = struct{}{}
		args.Imports = append(args.Imports, fmt.Sprintf("import '%s';", imp))
	}
	addImport(fmt.Sprintf("%s.proto", DependencyProto))

	outFilePath, _ := filepath.Abs(filepath.Join(outDir, strings.TrimSuffix(filepath.Base(file.Path), filepath.Ext(file.Path))+".proto"))

	for _, v := range viper.GetStringSlice("pb_imports") {
		impFilePath := v

		if !filepath.IsAbs(v) {
			impFilePath, _ = filepath.Abs(filepath.Join(outDir, v))
		}

		if impFilePath == outFilePath {
			continue
		}

		addImport(v)
	}
	for _, v := range collectDeclImports(file.Path, typeDecls, columnDecls) {
		addImport(v)
	}
	sort.Strings(args.Imports)

	for k, v := range viper.GetStringMapString("pb_options") {
		args.Options = append(args.Options, fmt.Sprintf("option %s='%s';", k, v))
	}
	sort.Strings(args.Options)

	typeDecls.Each(func(ty Type, decl *Decl) {
		if decl.IsEnum {
			args.Enums = append(args.Enums, decl)
		}
		if decl.IsStruct {
			args.Structs = append(args.Structs, decl)
		}
	})

	columnDecls.Each(func(ty Type, decl *Decl) {
		if decl.IsTable {
			args.Columns = append(args.Columns, decl)
		}
	})

	t := template.Must(template.New("proto").
		Funcs(template.FuncMap{
			"Incr":      func(n int) int { return n + 1 },
			"Add":       func(n ...int) int { return pie.Sum(n) },
			"TableName": func(s string) string { return strings.TrimSuffix(s, "Columns") + "Table" },
		}).
		Parse(tmpl))

	os.MkdirAll(outDir, os.ModePerm)

	outFile, err := os.OpenFile(outFilePath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, os.ModePerm)
	if err != nil {
		log.Panic(err)
	}
	defer outFile.Close()

	err = t.Execute(outFile, args)
	if err != nil {
		log.Panic(err)
	}
}

func collectDeclImports(currentFile string, declMaps ...*generic.SliceMap[Type, *Decl]) []string {
	currentFile, _ = filepath.Abs(currentFile)

	imports := map[string]struct{}{}

	var visitDecl func(decl *Decl)
	var visitField func(field *Field)

	visitDecl = func(decl *Decl) {
		if decl == nil || decl.IsBuiltin {
			return
		}

		if decl.File != "" {
			declFile, _ := filepath.Abs(decl.File)
			if declFile != currentFile {
				imports[strings.TrimSuffix(filepath.Base(decl.File), filepath.Ext(decl.File))+".proto"] = struct{}{}
			}
		}

		if decl.Child != nil {
			visitField(decl.Child)
		}
		if decl.Mapping != nil {
			visitDecl(decl.Mapping.K)
			visitDecl(decl.Mapping.V)
		}
		decl.Fields.Each(func(_ string, field *Field) {
			visitField(field)
		})
	}

	visitField = func(field *Field) {
		if field == nil {
			return
		}
		visitDecl(field.Decl)
	}

	for _, declMap := range declMaps {
		declMap.Each(func(_ Type, decl *Decl) {
			visitDecl(decl)
		})
	}

	out := make([]string, 0, len(imports))
	for imp := range imports {
		out = append(out, imp)
	}
	sort.Strings(out)

	return out
}
