// Code generated by 'yaegi extract git.golaxy.org/framework/addins/broker'. DO NOT EDIT.

package fwlib

import (
	"context"
	"git.golaxy.org/core/utils/async"
	"git.golaxy.org/framework/addins/broker"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/addins/broker/broker"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddIn":                           reflect.ValueOf(&broker.AddIn).Elem(),
		"DeliveryReliability_AtLeastOnce": reflect.ValueOf(broker.DeliveryReliability_AtLeastOnce),
		"DeliveryReliability_AtMostOnce":  reflect.ValueOf(broker.DeliveryReliability_AtMostOnce),

		// type definitions
		"DeliveryReliability": reflect.ValueOf((*broker.DeliveryReliability)(nil)),
		"Event":               reflect.ValueOf((*broker.Event)(nil)),
		"EventHandler":        reflect.ValueOf((*broker.EventHandler)(nil)),
		"IBroker":             reflect.ValueOf((*broker.IBroker)(nil)),

		// interface wrapper definitions
		"_IBroker": reflect.ValueOf((*_git_golaxy_org_framework_addins_broker_IBroker)(nil)),
	}
}

// _git_golaxy_org_framework_addins_broker_IBroker is an interface wrapper for IBroker type
type _git_golaxy_org_framework_addins_broker_IBroker struct {
	IValue               interface{}
	WDeliveryReliability func() broker.DeliveryReliability
	WFlush               func(ctx context.Context) error
	WMaxPayload          func() int64
	WPublish             func(ctx context.Context, topic string, data []byte) error
	WSeparator           func() string
	WSubscribeEvent      func(ctx context.Context, pattern string, queue string, autoAck ...bool) (<-chan broker.Event, error)
	WSubscribeHandler    func(ctx context.Context, pattern string, queue string, handler broker.EventHandler, autoAck ...bool) (async.Future, error)
}

func (W _git_golaxy_org_framework_addins_broker_IBroker) DeliveryReliability() broker.DeliveryReliability {
	return W.WDeliveryReliability()
}
func (W _git_golaxy_org_framework_addins_broker_IBroker) Flush(ctx context.Context) error {
	return W.WFlush(ctx)
}
func (W _git_golaxy_org_framework_addins_broker_IBroker) MaxPayload() int64 { return W.WMaxPayload() }
func (W _git_golaxy_org_framework_addins_broker_IBroker) Publish(ctx context.Context, topic string, data []byte) error {
	return W.WPublish(ctx, topic, data)
}
func (W _git_golaxy_org_framework_addins_broker_IBroker) Separator() string { return W.WSeparator() }
func (W _git_golaxy_org_framework_addins_broker_IBroker) SubscribeEvent(ctx context.Context, pattern string, queue string, autoAck ...bool) (<-chan broker.Event, error) {
	return W.WSubscribeEvent(ctx, pattern, queue, autoAck...)
}
func (W _git_golaxy_org_framework_addins_broker_IBroker) SubscribeHandler(ctx context.Context, pattern string, queue string, handler broker.EventHandler, autoAck ...bool) (async.Future, error) {
	return W.WSubscribeHandler(ctx, pattern, queue, handler, autoAck...)
}
