// Code generated by 'yaegi extract git.golaxy.org/framework/net/gap'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/framework/net/gap"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/net/gap/gap"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DefaultMsgCreator": reflect.ValueOf(gap.DefaultMsgCreator),
		"ErrGAP":            reflect.ValueOf(&gap.ErrGAP).Elem(),
		"ErrNotDeclared":    reflect.ValueOf(&gap.ErrNotDeclared).Elem(),
		"GenMsgID":          reflect.ValueOf(gap.GenMsgID),
		"MsgID_Customize":   reflect.ValueOf(constant.MakeFromLiteral("32", token.INT, 0)),
		"MsgID_Forward":     reflect.ValueOf(gap.MsgID_Forward),
		"MsgID_None":        reflect.ValueOf(gap.MsgID_None),
		"MsgID_OnewayRPC":   reflect.ValueOf(gap.MsgID_OnewayRPC),
		"MsgID_RPC_Reply":   reflect.ValueOf(gap.MsgID_RPC_Reply),
		"MsgID_RPC_Request": reflect.ValueOf(gap.MsgID_RPC_Request),
		"NewMsgCreator":     reflect.ValueOf(gap.NewMsgCreator),
		"Unmarshal":         reflect.ValueOf(gap.Unmarshal),

		// type definitions
		"IMsgCreator":   reflect.ValueOf((*gap.IMsgCreator)(nil)),
		"Msg":           reflect.ValueOf((*gap.Msg)(nil)),
		"MsgForward":    reflect.ValueOf((*gap.MsgForward)(nil)),
		"MsgHead":       reflect.ValueOf((*gap.MsgHead)(nil)),
		"MsgID":         reflect.ValueOf((*gap.MsgID)(nil)),
		"MsgOnewayRPC":  reflect.ValueOf((*gap.MsgOnewayRPC)(nil)),
		"MsgPacket":     reflect.ValueOf((*gap.MsgPacket)(nil)),
		"MsgRPCReply":   reflect.ValueOf((*gap.MsgRPCReply)(nil)),
		"MsgRPCRequest": reflect.ValueOf((*gap.MsgRPCRequest)(nil)),
		"Origin":        reflect.ValueOf((*gap.Origin)(nil)),
		"ReadableMsg":   reflect.ValueOf((*gap.ReadableMsg)(nil)),
		"SerializedMsg": reflect.ValueOf((*gap.SerializedMsg)(nil)),

		// interface wrapper definitions
		"_IMsgCreator": reflect.ValueOf((*_git_golaxy_org_framework_net_gap_IMsgCreator)(nil)),
		"_Msg":         reflect.ValueOf((*_git_golaxy_org_framework_net_gap_Msg)(nil)),
		"_ReadableMsg": reflect.ValueOf((*_git_golaxy_org_framework_net_gap_ReadableMsg)(nil)),
	}
}

// _git_golaxy_org_framework_net_gap_IMsgCreator is an interface wrapper for IMsgCreator type
type _git_golaxy_org_framework_net_gap_IMsgCreator struct {
	IValue   interface{}
	WDeclare func(msg gap.Msg)
	WNew     func(msgID gap.MsgID) (gap.Msg, error)
}

func (W _git_golaxy_org_framework_net_gap_IMsgCreator) Declare(msg gap.Msg) { W.WDeclare(msg) }
func (W _git_golaxy_org_framework_net_gap_IMsgCreator) New(msgID gap.MsgID) (gap.Msg, error) {
	return W.WNew(msgID)
}

// _git_golaxy_org_framework_net_gap_Msg is an interface wrapper for Msg type
type _git_golaxy_org_framework_net_gap_Msg struct {
	IValue interface{}
	WMsgID func() gap.MsgID
	WRead  func(p []byte) (n int, err error)
	WSize  func() int
	WWrite func(p []byte) (n int, err error)
}

func (W _git_golaxy_org_framework_net_gap_Msg) MsgID() gap.MsgID                  { return W.WMsgID() }
func (W _git_golaxy_org_framework_net_gap_Msg) Read(p []byte) (n int, err error)  { return W.WRead(p) }
func (W _git_golaxy_org_framework_net_gap_Msg) Size() int                         { return W.WSize() }
func (W _git_golaxy_org_framework_net_gap_Msg) Write(p []byte) (n int, err error) { return W.WWrite(p) }

// _git_golaxy_org_framework_net_gap_ReadableMsg is an interface wrapper for ReadableMsg type
type _git_golaxy_org_framework_net_gap_ReadableMsg struct {
	IValue interface{}
	WMsgID func() gap.MsgID
	WRead  func(p []byte) (n int, err error)
	WSize  func() int
}

func (W _git_golaxy_org_framework_net_gap_ReadableMsg) MsgID() gap.MsgID { return W.WMsgID() }
func (W _git_golaxy_org_framework_net_gap_ReadableMsg) Read(p []byte) (n int, err error) {
	return W.WRead(p)
}
func (W _git_golaxy_org_framework_net_gap_ReadableMsg) Size() int { return W.WSize() }
