// Code generated by 'yaegi extract git.golaxy.org/framework/addins/gate/cli'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/framework/addins/gate/cli"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/addins/gate/cli/cli"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Connect":            reflect.ValueOf(cli.Connect),
		"ErrInactiveTimeout": reflect.ValueOf(&cli.ErrInactiveTimeout).Elem(),
		"ErrReconnectFailed": reflect.ValueOf(&cli.ErrReconnectFailed).Elem(),
		"Reconnect":          reflect.ValueOf(cli.Reconnect),
		"TCP":                reflect.ValueOf(cli.TCP),
		"WebSocket":          reflect.ValueOf(cli.WebSocket),
		"With":               reflect.ValueOf(&cli.With).Elem(),

		// type definitions
		"Client":           reflect.ValueOf((*cli.Client)(nil)),
		"ClientOptions":    reflect.ValueOf((*cli.ClientOptions)(nil)),
		"NetProtocol":      reflect.ValueOf((*cli.NetProtocol)(nil)),
		"RecvDataHandler":  reflect.ValueOf((*cli.RecvDataHandler)(nil)),
		"RecvEventHandler": reflect.ValueOf((*cli.RecvEventHandler)(nil)),
		"ResponseTime":     reflect.ValueOf((*cli.ResponseTime)(nil)),
	}
}
