// Code generated by 'yaegi extract git.golaxy.org/framework/net/gap/variant'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/framework/net/gap/variant"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/net/gap/variant/variant"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ErrInvalidCast":      reflect.ValueOf(&variant.ErrInvalidCast).Elem(),
		"ErrNotDeclared":      reflect.ValueOf(&variant.ErrNotDeclared).Elem(),
		"ErrSnapshotReadonly": reflect.ValueOf(&variant.ErrSnapshotReadonly).Elem(),
		"ErrVariant":          reflect.ValueOf(&variant.ErrVariant).Elem(),
		"Errorf":              reflect.ValueOf(variant.Errorf),
		"Errorln":             reflect.ValueOf(variant.Errorln),
		"GenTypeID":           reflect.ValueOf(variant.GenTypeID),
		"NewError":            reflect.ValueOf(variant.NewError),
		"NewVariant":          reflect.ValueOf(variant.NewVariant),
		"ToVariant":           reflect.ValueOf(variant.ToVariant),
		"TypeID_Array":        reflect.ValueOf(variant.TypeID_Array),
		"TypeID_Bool":         reflect.ValueOf(variant.TypeID_Bool),
		"TypeID_Byte":         reflect.ValueOf(variant.TypeID_Byte),
		"TypeID_Bytes":        reflect.ValueOf(variant.TypeID_Bytes),
		"TypeID_CallChain":    reflect.ValueOf(variant.TypeID_CallChain),
		"TypeID_Customize":    reflect.ValueOf(constant.MakeFromLiteral("32", token.INT, 0)),
		"TypeID_Double":       reflect.ValueOf(variant.TypeID_Double),
		"TypeID_Error":        reflect.ValueOf(variant.TypeID_Error),
		"TypeID_Float":        reflect.ValueOf(variant.TypeID_Float),
		"TypeID_Int":          reflect.ValueOf(variant.TypeID_Int),
		"TypeID_Int16":        reflect.ValueOf(variant.TypeID_Int16),
		"TypeID_Int32":        reflect.ValueOf(variant.TypeID_Int32),
		"TypeID_Int64":        reflect.ValueOf(variant.TypeID_Int64),
		"TypeID_Int8":         reflect.ValueOf(variant.TypeID_Int8),
		"TypeID_Map":          reflect.ValueOf(variant.TypeID_Map),
		"TypeID_None":         reflect.ValueOf(variant.TypeID_None),
		"TypeID_Null":         reflect.ValueOf(variant.TypeID_Null),
		"TypeID_String":       reflect.ValueOf(variant.TypeID_String),
		"TypeID_Uint":         reflect.ValueOf(variant.TypeID_Uint),
		"TypeID_Uint16":       reflect.ValueOf(variant.TypeID_Uint16),
		"TypeID_Uint32":       reflect.ValueOf(variant.TypeID_Uint32),
		"TypeID_Uint64":       reflect.ValueOf(variant.TypeID_Uint64),
		"TypeID_Uint8":        reflect.ValueOf(variant.TypeID_Uint8),
		"VariantCreator":      reflect.ValueOf(variant.VariantCreator),

		// type definitions
		"Array":           reflect.ValueOf((*variant.Array)(nil)),
		"Bool":            reflect.ValueOf((*variant.Bool)(nil)),
		"Byte":            reflect.ValueOf((*variant.Byte)(nil)),
		"Bytes":           reflect.ValueOf((*variant.Bytes)(nil)),
		"Call":            reflect.ValueOf((*variant.Call)(nil)),
		"CallChain":       reflect.ValueOf((*variant.CallChain)(nil)),
		"Double":          reflect.ValueOf((*variant.Double)(nil)),
		"Error":           reflect.ValueOf((*variant.Error)(nil)),
		"Float":           reflect.ValueOf((*variant.Float)(nil)),
		"IVariantCreator": reflect.ValueOf((*variant.IVariantCreator)(nil)),
		"Int":             reflect.ValueOf((*variant.Int)(nil)),
		"Int16":           reflect.ValueOf((*variant.Int16)(nil)),
		"Int32":           reflect.ValueOf((*variant.Int32)(nil)),
		"Int64":           reflect.ValueOf((*variant.Int64)(nil)),
		"Int8":            reflect.ValueOf((*variant.Int8)(nil)),
		"Map":             reflect.ValueOf((*variant.Map)(nil)),
		"Null":            reflect.ValueOf((*variant.Null)(nil)),
		"ReadableValue":   reflect.ValueOf((*variant.ReadableValue)(nil)),
		"String":          reflect.ValueOf((*variant.String)(nil)),
		"TypeID":          reflect.ValueOf((*variant.TypeID)(nil)),
		"Uint":            reflect.ValueOf((*variant.Uint)(nil)),
		"Uint16":          reflect.ValueOf((*variant.Uint16)(nil)),
		"Uint32":          reflect.ValueOf((*variant.Uint32)(nil)),
		"Uint64":          reflect.ValueOf((*variant.Uint64)(nil)),
		"Uint8":           reflect.ValueOf((*variant.Uint8)(nil)),
		"Value":           reflect.ValueOf((*variant.Value)(nil)),
		"Variant":         reflect.ValueOf((*variant.Variant)(nil)),

		// interface wrapper definitions
		"_IVariantCreator": reflect.ValueOf((*_git_golaxy_org_framework_net_gap_variant_IVariantCreator)(nil)),
		"_ReadableValue":   reflect.ValueOf((*_git_golaxy_org_framework_net_gap_variant_ReadableValue)(nil)),
		"_Value":           reflect.ValueOf((*_git_golaxy_org_framework_net_gap_variant_Value)(nil)),
	}
}

// _git_golaxy_org_framework_net_gap_variant_IVariantCreator is an interface wrapper for IVariantCreator type
type _git_golaxy_org_framework_net_gap_variant_IVariantCreator struct {
	IValue        interface{}
	WDeclare      func(v variant.Value)
	WNew          func(typeID variant.TypeID) (variant.Value, error)
	WNewReflected func(typeID variant.TypeID) (reflect.Value, error)
}

func (W _git_golaxy_org_framework_net_gap_variant_IVariantCreator) Declare(v variant.Value) {
	W.WDeclare(v)
}
func (W _git_golaxy_org_framework_net_gap_variant_IVariantCreator) New(typeID variant.TypeID) (variant.Value, error) {
	return W.WNew(typeID)
}
func (W _git_golaxy_org_framework_net_gap_variant_IVariantCreator) NewReflected(typeID variant.TypeID) (reflect.Value, error) {
	return W.WNewReflected(typeID)
}

// _git_golaxy_org_framework_net_gap_variant_ReadableValue is an interface wrapper for ReadableValue type
type _git_golaxy_org_framework_net_gap_variant_ReadableValue struct {
	IValue    interface{}
	WIndirect func() any
	WRead     func(p []byte) (n int, err error)
	WSize     func() int
	WTypeID   func() variant.TypeID
}

func (W _git_golaxy_org_framework_net_gap_variant_ReadableValue) Indirect() any { return W.WIndirect() }
func (W _git_golaxy_org_framework_net_gap_variant_ReadableValue) Read(p []byte) (n int, err error) {
	return W.WRead(p)
}
func (W _git_golaxy_org_framework_net_gap_variant_ReadableValue) Size() int { return W.WSize() }
func (W _git_golaxy_org_framework_net_gap_variant_ReadableValue) TypeID() variant.TypeID {
	return W.WTypeID()
}

// _git_golaxy_org_framework_net_gap_variant_Value is an interface wrapper for Value type
type _git_golaxy_org_framework_net_gap_variant_Value struct {
	IValue    interface{}
	WIndirect func() any
	WRead     func(p []byte) (n int, err error)
	WSize     func() int
	WTypeID   func() variant.TypeID
	WWrite    func(p []byte) (n int, err error)
}

func (W _git_golaxy_org_framework_net_gap_variant_Value) Indirect() any { return W.WIndirect() }
func (W _git_golaxy_org_framework_net_gap_variant_Value) Read(p []byte) (n int, err error) {
	return W.WRead(p)
}
func (W _git_golaxy_org_framework_net_gap_variant_Value) Size() int              { return W.WSize() }
func (W _git_golaxy_org_framework_net_gap_variant_Value) TypeID() variant.TypeID { return W.WTypeID() }
func (W _git_golaxy_org_framework_net_gap_variant_Value) Write(p []byte) (n int, err error) {
	return W.WWrite(p)
}
