// Code generated by 'yaegi extract git.golaxy.org/framework/utils/correlation'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/framework/utils/correlation"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/utils/correlation/correlation"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ErrClosed":  reflect.ValueOf(&correlation.ErrClosed).Elem(),
		"ErrTimeout": reflect.ValueOf(&correlation.ErrTimeout).Elem(),
		"New":        reflect.ValueOf(correlation.New),

		// type definitions
		"Controller": reflect.ValueOf((*correlation.Controller)(nil)),
		"ID":         reflect.ValueOf((*correlation.ID)(nil)),
	}
}
