// Code generated by 'yaegi extract git.golaxy.org/core/utils/corectx'. DO NOT EDIT.

package fwlib

import (
	"context"
	"git.golaxy.org/core/utils/async"
	"git.golaxy.org/core/utils/corectx"
	"git.golaxy.org/core/utils/iface"
	"reflect"
	"time"
)

func init() {
	Symbols["git.golaxy.org/core/utils/corectx/corectx"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"UnsafeContext": reflect.ValueOf(corectx.UnsafeContext),

		// type definitions
		"ConcurrentContextProvider": reflect.ValueOf((*corectx.ConcurrentContextProvider)(nil)),
		"Context":                   reflect.ValueOf((*corectx.Context)(nil)),
		"ContextBehavior":           reflect.ValueOf((*corectx.ContextBehavior)(nil)),
		"CurrentContextProvider":    reflect.ValueOf((*corectx.CurrentContextProvider)(nil)),
		"WaitGroup":                 reflect.ValueOf((*corectx.WaitGroup)(nil)),

		// interface wrapper definitions
		"_ConcurrentContextProvider": reflect.ValueOf((*_git_golaxy_org_core_utils_corectx_ConcurrentContextProvider)(nil)),
		"_Context":                   reflect.ValueOf((*_git_golaxy_org_core_utils_corectx_Context)(nil)),
		"_CurrentContextProvider":    reflect.ValueOf((*_git_golaxy_org_core_utils_corectx_CurrentContextProvider)(nil)),
		"_WaitGroup":                 reflect.ValueOf((*_git_golaxy_org_core_utils_corectx_WaitGroup)(nil)),
	}
}

// _git_golaxy_org_core_utils_corectx_ConcurrentContextProvider is an interface wrapper for ConcurrentContextProvider type
type _git_golaxy_org_core_utils_corectx_ConcurrentContextProvider struct {
	IValue             interface{}
	WConcurrentContext func() iface.Cache
}

func (W _git_golaxy_org_core_utils_corectx_ConcurrentContextProvider) ConcurrentContext() iface.Cache {
	return W.WConcurrentContext()
}

// _git_golaxy_org_core_utils_corectx_Context is an interface wrapper for Context type
type _git_golaxy_org_core_utils_corectx_Context struct {
	IValue         interface{}
	WAutoRecover   func() bool
	WDeadline      func() (deadline time.Time, ok bool)
	WDone          func() <-chan struct{}
	WErr           func() error
	WParentContext func() context.Context
	WReportError   func() chan error
	WTerminate     func() async.Future
	WTerminated    func() async.Future
	WValue         func(key any) any
	WWaitGroup     func() corectx.WaitGroup
}

func (W _git_golaxy_org_core_utils_corectx_Context) AutoRecover() bool { return W.WAutoRecover() }
func (W _git_golaxy_org_core_utils_corectx_Context) Deadline() (deadline time.Time, ok bool) {
	return W.WDeadline()
}
func (W _git_golaxy_org_core_utils_corectx_Context) Done() <-chan struct{} { return W.WDone() }
func (W _git_golaxy_org_core_utils_corectx_Context) Err() error            { return W.WErr() }
func (W _git_golaxy_org_core_utils_corectx_Context) ParentContext() context.Context {
	return W.WParentContext()
}
func (W _git_golaxy_org_core_utils_corectx_Context) ReportError() chan error  { return W.WReportError() }
func (W _git_golaxy_org_core_utils_corectx_Context) Terminate() async.Future  { return W.WTerminate() }
func (W _git_golaxy_org_core_utils_corectx_Context) Terminated() async.Future { return W.WTerminated() }
func (W _git_golaxy_org_core_utils_corectx_Context) Value(key any) any        { return W.WValue(key) }
func (W _git_golaxy_org_core_utils_corectx_Context) WaitGroup() corectx.WaitGroup {
	return W.WWaitGroup()
}

// _git_golaxy_org_core_utils_corectx_CurrentContextProvider is an interface wrapper for CurrentContextProvider type
type _git_golaxy_org_core_utils_corectx_CurrentContextProvider struct {
	IValue             interface{}
	WConcurrentContext func() iface.Cache
	WCurrentContext    func() iface.Cache
}

func (W _git_golaxy_org_core_utils_corectx_CurrentContextProvider) ConcurrentContext() iface.Cache {
	return W.WConcurrentContext()
}
func (W _git_golaxy_org_core_utils_corectx_CurrentContextProvider) CurrentContext() iface.Cache {
	return W.WCurrentContext()
}

// _git_golaxy_org_core_utils_corectx_WaitGroup is an interface wrapper for WaitGroup type
type _git_golaxy_org_core_utils_corectx_WaitGroup struct {
	IValue  interface{}
	WClosed func() bool
	WCount  func() int64
	WDone   func()
	WJoin   func(delta int64) bool
	WWait   func()
}

func (W _git_golaxy_org_core_utils_corectx_WaitGroup) Closed() bool          { return W.WClosed() }
func (W _git_golaxy_org_core_utils_corectx_WaitGroup) Count() int64          { return W.WCount() }
func (W _git_golaxy_org_core_utils_corectx_WaitGroup) Done()                 { W.WDone() }
func (W _git_golaxy_org_core_utils_corectx_WaitGroup) Join(delta int64) bool { return W.WJoin(delta) }
func (W _git_golaxy_org_core_utils_corectx_WaitGroup) Wait()                 { W.WWait() }
