// Code generated by 'yaegi extract git.golaxy.org/core/utils/meta'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/core/utils/meta"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/core/utils/meta/meta"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BuildMeta": reflect.ValueOf(meta.BuildMeta),

		// type definitions
		"Meta":        reflect.ValueOf((*meta.Meta)(nil)),
		"MetaCreator": reflect.ValueOf((*meta.MetaCreator)(nil)),
	}
}
