// Code generated by 'yaegi extract git.golaxy.org/framework/addins/discovery'. DO NOT EDIT.

package fwlib

import (
	"context"
	"git.golaxy.org/core/utils/async"
	"git.golaxy.org/core/utils/uid"
	"git.golaxy.org/framework/addins/discovery"
	"reflect"
	"time"
)

func init() {
	Symbols["git.golaxy.org/framework/addins/discovery/discovery"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddIn":                    reflect.ValueOf(&discovery.AddIn).Elem(),
		"ErrDuplicateRegistration": reflect.ValueOf(&discovery.ErrDuplicateRegistration).Elem(),
		"ErrRegistrationNotFound":  reflect.ValueOf(&discovery.ErrRegistrationNotFound).Elem(),
		"EventType_Create":         reflect.ValueOf(discovery.EventType_Create),
		"EventType_Delete":         reflect.ValueOf(discovery.EventType_Delete),
		"EventType_Error":          reflect.ValueOf(discovery.EventType_Error),
		"EventType_Update":         reflect.ValueOf(discovery.EventType_Update),

		// type definitions
		"Event":         reflect.ValueOf((*discovery.Event)(nil)),
		"EventHandler":  reflect.ValueOf((*discovery.EventHandler)(nil)),
		"EventType":     reflect.ValueOf((*discovery.EventType)(nil)),
		"IRegistration": reflect.ValueOf((*discovery.IRegistration)(nil)),
		"IRegistry":     reflect.ValueOf((*discovery.IRegistry)(nil)),
		"Node":          reflect.ValueOf((*discovery.Node)(nil)),
		"Service":       reflect.ValueOf((*discovery.Service)(nil)),

		// interface wrapper definitions
		"_IRegistration": reflect.ValueOf((*_git_golaxy_org_framework_addins_discovery_IRegistration)(nil)),
		"_IRegistry":     reflect.ValueOf((*_git_golaxy_org_framework_addins_discovery_IRegistry)(nil)),
	}
}

// _git_golaxy_org_framework_addins_discovery_IRegistration is an interface wrapper for IRegistration type
type _git_golaxy_org_framework_addins_discovery_IRegistration struct {
	IValue               interface{}
	WDeregister          func(ctx context.Context) error
	WKeepAliveContinuous func(ctx context.Context) (async.Future, error)
	WKeepAliveOnce       func(ctx context.Context) error
}

func (W _git_golaxy_org_framework_addins_discovery_IRegistration) Deregister(ctx context.Context) error {
	return W.WDeregister(ctx)
}
func (W _git_golaxy_org_framework_addins_discovery_IRegistration) KeepAliveContinuous(ctx context.Context) (async.Future, error) {
	return W.WKeepAliveContinuous(ctx)
}
func (W _git_golaxy_org_framework_addins_discovery_IRegistration) KeepAliveOnce(ctx context.Context) error {
	return W.WKeepAliveOnce(ctx)
}

// _git_golaxy_org_framework_addins_discovery_IRegistry is an interface wrapper for IRegistry type
type _git_golaxy_org_framework_addins_discovery_IRegistry struct {
	IValue        interface{}
	WGet          func(ctx context.Context, serviceName string) (*discovery.Service, error)
	WGetNode      func(ctx context.Context, serviceName string, nodeId uid.Id) (*discovery.Service, error)
	WList         func(ctx context.Context) ([]*discovery.Service, error)
	WRegisterNode func(ctx context.Context, serviceName string, node *discovery.Node, ttl time.Duration) (discovery.IRegistration, error)
	WWatchEvent   func(ctx context.Context, pattern string, revision ...int64) (<-chan discovery.Event, error)
	WWatchHandler func(ctx context.Context, pattern string, handler discovery.EventHandler, revision ...int64) (async.Future, error)
}

func (W _git_golaxy_org_framework_addins_discovery_IRegistry) Get(ctx context.Context, serviceName string) (*discovery.Service, error) {
	return W.WGet(ctx, serviceName)
}
func (W _git_golaxy_org_framework_addins_discovery_IRegistry) GetNode(ctx context.Context, serviceName string, nodeId uid.Id) (*discovery.Service, error) {
	return W.WGetNode(ctx, serviceName, nodeId)
}
func (W _git_golaxy_org_framework_addins_discovery_IRegistry) List(ctx context.Context) ([]*discovery.Service, error) {
	return W.WList(ctx)
}
func (W _git_golaxy_org_framework_addins_discovery_IRegistry) RegisterNode(ctx context.Context, serviceName string, node *discovery.Node, ttl time.Duration) (discovery.IRegistration, error) {
	return W.WRegisterNode(ctx, serviceName, node, ttl)
}
func (W _git_golaxy_org_framework_addins_discovery_IRegistry) WatchEvent(ctx context.Context, pattern string, revision ...int64) (<-chan discovery.Event, error) {
	return W.WWatchEvent(ctx, pattern, revision...)
}
func (W _git_golaxy_org_framework_addins_discovery_IRegistry) WatchHandler(ctx context.Context, pattern string, handler discovery.EventHandler, revision ...int64) (async.Future, error) {
	return W.WWatchHandler(ctx, pattern, handler, revision...)
}
