// Code generated by 'yaegi extract git.golaxy.org/framework/addins/db/sqldb'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/framework/addins/db/sqldb"
	"gorm.io/gorm"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/addins/db/sqldb/sqldb"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddIn": reflect.ValueOf(&sqldb.AddIn).Elem(),
		"DB":    reflect.ValueOf(sqldb.DB),
		"With":  reflect.ValueOf(&sqldb.With).Elem(),

		// type definitions
		"ISQLDB":       reflect.ValueOf((*sqldb.ISQLDB)(nil)),
		"SQLDBOptions": reflect.ValueOf((*sqldb.SQLDBOptions)(nil)),

		// interface wrapper definitions
		"_ISQLDB": reflect.ValueOf((*_git_golaxy_org_framework_addins_db_sqldb_ISQLDB)(nil)),
	}
}

// _git_golaxy_org_framework_addins_db_sqldb_ISQLDB is an interface wrapper for ISQLDB type
type _git_golaxy_org_framework_addins_db_sqldb_ISQLDB struct {
	IValue       interface{}
	WDB          func(tag string) *gorm.DB
	WReflectedDB func(tag string) reflect.Value
}

func (W _git_golaxy_org_framework_addins_db_sqldb_ISQLDB) DB(tag string) *gorm.DB { return W.WDB(tag) }
func (W _git_golaxy_org_framework_addins_db_sqldb_ISQLDB) ReflectedDB(tag string) reflect.Value {
	return W.WReflectedDB(tag)
}
