// Code generated by 'yaegi extract git.golaxy.org/core/utils/async'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/core/utils/async"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/core/utils/async/async"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ErrFutureClosed": reflect.ValueOf(&async.ErrFutureClosed).Elem(),
		"NewFutureChan":   reflect.ValueOf(async.NewFutureChan),
		"NewFutureVoid":   reflect.ValueOf(async.NewFutureVoid),
		"NewResult":       reflect.ValueOf(async.NewResult),
		"Return":          reflect.ValueOf(async.Return),
		"ReturnVoid":      reflect.ValueOf(async.ReturnVoid),
		"YieldBreak":      reflect.ValueOf(async.YieldBreak),
		"YieldReturn":     reflect.ValueOf(async.YieldReturn),

		// type definitions
		"Future":     reflect.ValueOf((*async.Future)(nil)),
		"FutureChan": reflect.ValueOf((*async.FutureChan)(nil)),
		"FutureVoid": reflect.ValueOf((*async.FutureVoid)(nil)),
		"Result":     reflect.ValueOf((*async.Result)(nil)),
	}
}
