// Code generated by 'yaegi extract git.golaxy.org/framework/addins/db'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/framework/addins/db"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/addins/db/db"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"InjectDB":   reflect.ValueOf(db.InjectDB),
		"InjectDBRV": reflect.ValueOf(db.InjectDBRV),
		"MigrateDB":  reflect.ValueOf(db.MigrateDB),
		"MongoDB":    reflect.ValueOf(db.MongoDB),
		"RedisDB":    reflect.ValueOf(db.RedisDB),
		"SQLDB":      reflect.ValueOf(db.SQLDB),

		// type definitions
		"IMigrateDB": reflect.ValueOf((*db.IMigrateDB)(nil)),

		// interface wrapper definitions
		"_IMigrateDB": reflect.ValueOf((*_git_golaxy_org_framework_addins_db_IMigrateDB)(nil)),
	}
}

// _git_golaxy_org_framework_addins_db_IMigrateDB is an interface wrapper for IMigrateDB type
type _git_golaxy_org_framework_addins_db_IMigrateDB struct {
	IValue     interface{}
	WMigrateDB func() error
}

func (W _git_golaxy_org_framework_addins_db_IMigrateDB) MigrateDB() error { return W.WMigrateDB() }
