// Code generated by 'yaegi extract git.golaxy.org/core/utils/meta'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/core/utils/meta"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/core/utils/meta/meta"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"B":     reflect.ValueOf(meta.B),
		"Build": reflect.ValueOf(meta.Build),
		"M":     reflect.ValueOf(meta.M),
		"Make":  reflect.ValueOf(meta.Make),
		"N":     reflect.ValueOf(meta.N),
		"New":   reflect.ValueOf(meta.New),

		// type definitions
		"Meta":        reflect.ValueOf((*meta.Meta)(nil)),
		"MetaCreator": reflect.ValueOf((*meta.MetaCreator)(nil)),
	}
}
