// Code generated by 'yaegi extract git.golaxy.org/core/extension'. DO NOT EDIT.

package fwlib

import (
	"context"
	"git.golaxy.org/core/event"
	"git.golaxy.org/core/extension"
	"git.golaxy.org/core/utils/async"
	"git.golaxy.org/core/utils/iface"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/core/extension/extension"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddInState_Loaded":                   reflect.ValueOf(extension.AddInState_Loaded),
		"AddInState_Running":                  reflect.ValueOf(extension.AddInState_Running),
		"AddInState_Unloaded":                 reflect.ValueOf(extension.AddInState_Unloaded),
		"BindEventRuntimeAddInStateChanged":   reflect.ValueOf(extension.BindEventRuntimeAddInStateChanged),
		"BindEventRuntimeInstallAddIn":        reflect.ValueOf(extension.BindEventRuntimeInstallAddIn),
		"BindEventRuntimeUninstallAddIn":      reflect.ValueOf(extension.BindEventRuntimeUninstallAddIn),
		"ErrExtension":                        reflect.ValueOf(&extension.ErrExtension).Elem(),
		"EventRuntimeAddInStateChangedId":     reflect.ValueOf(&extension.EventRuntimeAddInStateChangedId).Elem(),
		"EventRuntimeInstallAddInId":          reflect.ValueOf(&extension.EventRuntimeInstallAddInId).Elem(),
		"EventRuntimeUninstallAddInId":        reflect.ValueOf(&extension.EventRuntimeUninstallAddInId).Elem(),
		"GenAddInId":                          reflect.ValueOf(extension.GenAddInId),
		"GenAddInName":                        reflect.ValueOf(extension.GenAddInName),
		"HandleEventRuntimeAddInStateChanged": reflect.ValueOf(extension.HandleEventRuntimeAddInStateChanged),
		"HandleEventRuntimeInstallAddIn":      reflect.ValueOf(extension.HandleEventRuntimeInstallAddIn),
		"HandleEventRuntimeUninstallAddIn":    reflect.ValueOf(extension.HandleEventRuntimeUninstallAddIn),
		"NewRuntimeAddInManager":              reflect.ValueOf(extension.NewRuntimeAddInManager),
		"NewServiceAddInManager":              reflect.ValueOf(extension.NewServiceAddInManager),
		"Uninstall":                           reflect.ValueOf(extension.Uninstall),
		"UnsafeRuntimeAddInManager":           reflect.ValueOf(extension.UnsafeRuntimeAddInManager),
		"UnsafeRuntimeAddInStatus":            reflect.ValueOf(extension.UnsafeRuntimeAddInStatus),
		"UnsafeServiceAddInManager":           reflect.ValueOf(extension.UnsafeServiceAddInManager),
		"UnsafeServiceAddInStatus":            reflect.ValueOf(extension.UnsafeServiceAddInStatus),

		// type definitions
		"AddInManager":                         reflect.ValueOf((*extension.AddInManager)(nil)),
		"AddInProvider":                        reflect.ValueOf((*extension.AddInProvider)(nil)),
		"AddInState":                           reflect.ValueOf((*extension.AddInState)(nil)),
		"AddInStatus":                          reflect.ValueOf((*extension.AddInStatus)(nil)),
		"EventRuntimeAddInStateChanged":        reflect.ValueOf((*extension.EventRuntimeAddInStateChanged)(nil)),
		"EventRuntimeAddInStateChangedHandler": reflect.ValueOf((*extension.EventRuntimeAddInStateChangedHandler)(nil)),
		"EventRuntimeInstallAddIn":             reflect.ValueOf((*extension.EventRuntimeInstallAddIn)(nil)),
		"EventRuntimeInstallAddInHandler":      reflect.ValueOf((*extension.EventRuntimeInstallAddInHandler)(nil)),
		"EventRuntimeUninstallAddIn":           reflect.ValueOf((*extension.EventRuntimeUninstallAddIn)(nil)),
		"EventRuntimeUninstallAddInHandler":    reflect.ValueOf((*extension.EventRuntimeUninstallAddInHandler)(nil)),
		"EventServiceAddInSnapshot":            reflect.ValueOf((*extension.EventServiceAddInSnapshot)(nil)),
		"EventServiceInstallAddIn":             reflect.ValueOf((*extension.EventServiceInstallAddIn)(nil)),
		"EventServiceUninstallAddIn":           reflect.ValueOf((*extension.EventServiceUninstallAddIn)(nil)),
		"IRuntimeAddInManagerEventTab":         reflect.ValueOf((*extension.IRuntimeAddInManagerEventTab)(nil)),
		"RuntimeAddInManager":                  reflect.ValueOf((*extension.RuntimeAddInManager)(nil)),
		"RuntimeAddInStatus":                   reflect.ValueOf((*extension.RuntimeAddInStatus)(nil)),
		"ServiceAddInManager":                  reflect.ValueOf((*extension.ServiceAddInManager)(nil)),
		"ServiceAddInStatus":                   reflect.ValueOf((*extension.ServiceAddInStatus)(nil)),

		// interface wrapper definitions
		"_AddInManager":                  reflect.ValueOf((*_git_golaxy_org_core_extension_AddInManager)(nil)),
		"_AddInProvider":                 reflect.ValueOf((*_git_golaxy_org_core_extension_AddInProvider)(nil)),
		"_AddInStatus":                   reflect.ValueOf((*_git_golaxy_org_core_extension_AddInStatus)(nil)),
		"_EventRuntimeAddInStateChanged": reflect.ValueOf((*_git_golaxy_org_core_extension_EventRuntimeAddInStateChanged)(nil)),
		"_EventRuntimeInstallAddIn":      reflect.ValueOf((*_git_golaxy_org_core_extension_EventRuntimeInstallAddIn)(nil)),
		"_EventRuntimeUninstallAddIn":    reflect.ValueOf((*_git_golaxy_org_core_extension_EventRuntimeUninstallAddIn)(nil)),
		"_IRuntimeAddInManagerEventTab":  reflect.ValueOf((*_git_golaxy_org_core_extension_IRuntimeAddInManagerEventTab)(nil)),
		"_RuntimeAddInManager":           reflect.ValueOf((*_git_golaxy_org_core_extension_RuntimeAddInManager)(nil)),
		"_RuntimeAddInStatus":            reflect.ValueOf((*_git_golaxy_org_core_extension_RuntimeAddInStatus)(nil)),
		"_ServiceAddInManager":           reflect.ValueOf((*_git_golaxy_org_core_extension_ServiceAddInManager)(nil)),
		"_ServiceAddInStatus":            reflect.ValueOf((*_git_golaxy_org_core_extension_ServiceAddInStatus)(nil)),
	}
}

// _git_golaxy_org_core_extension_AddInManager is an interface wrapper for AddInManager type
type _git_golaxy_org_core_extension_AddInManager struct {
	IValue           interface{}
	WAddInManager    func() extension.AddInManager
	WGetStatusById   func(id uint64) (extension.AddInStatus, bool)
	WGetStatusByName func(name string) (extension.AddInStatus, bool)
	WInstall         func(addInFace iface.FaceAny, name ...string) extension.AddInStatus
	WListStatuses    func() []extension.AddInStatus
	WUninstall       func(name string)
}

func (W _git_golaxy_org_core_extension_AddInManager) AddInManager() extension.AddInManager {
	return W.WAddInManager()
}
func (W _git_golaxy_org_core_extension_AddInManager) GetStatusById(id uint64) (extension.AddInStatus, bool) {
	return W.WGetStatusById(id)
}
func (W _git_golaxy_org_core_extension_AddInManager) GetStatusByName(name string) (extension.AddInStatus, bool) {
	return W.WGetStatusByName(name)
}
func (W _git_golaxy_org_core_extension_AddInManager) Install(addInFace iface.FaceAny, name ...string) extension.AddInStatus {
	return W.WInstall(addInFace, name...)
}
func (W _git_golaxy_org_core_extension_AddInManager) ListStatuses() []extension.AddInStatus {
	return W.WListStatuses()
}
func (W _git_golaxy_org_core_extension_AddInManager) Uninstall(name string) { W.WUninstall(name) }

// _git_golaxy_org_core_extension_AddInProvider is an interface wrapper for AddInProvider type
type _git_golaxy_org_core_extension_AddInProvider struct {
	IValue        interface{}
	WAddInManager func() extension.AddInManager
}

func (W _git_golaxy_org_core_extension_AddInProvider) AddInManager() extension.AddInManager {
	return W.WAddInManager()
}

// _git_golaxy_org_core_extension_AddInStatus is an interface wrapper for AddInStatus type
type _git_golaxy_org_core_extension_AddInStatus struct {
	IValue        interface{}
	WId           func() uint64
	WInstanceFace func() iface.FaceAny
	WName         func() string
	WReflected    func() reflect.Value
	WState        func() extension.AddInState
	WString       func() string
}

func (W _git_golaxy_org_core_extension_AddInStatus) Id() uint64 { return W.WId() }
func (W _git_golaxy_org_core_extension_AddInStatus) InstanceFace() iface.FaceAny {
	return W.WInstanceFace()
}
func (W _git_golaxy_org_core_extension_AddInStatus) Name() string                { return W.WName() }
func (W _git_golaxy_org_core_extension_AddInStatus) Reflected() reflect.Value    { return W.WReflected() }
func (W _git_golaxy_org_core_extension_AddInStatus) State() extension.AddInState { return W.WState() }
func (W _git_golaxy_org_core_extension_AddInStatus) String() string {
	if W.WString == nil {
		return ""
	}
	return W.WString()
}

// _git_golaxy_org_core_extension_EventRuntimeAddInStateChanged is an interface wrapper for EventRuntimeAddInStateChanged type
type _git_golaxy_org_core_extension_EventRuntimeAddInStateChanged struct {
	IValue                      interface{}
	WOnRuntimeAddInStateChanged func(status extension.RuntimeAddInStatus, state extension.AddInState)
}

func (W _git_golaxy_org_core_extension_EventRuntimeAddInStateChanged) OnRuntimeAddInStateChanged(status extension.RuntimeAddInStatus, state extension.AddInState) {
	W.WOnRuntimeAddInStateChanged(status, state)
}

// _git_golaxy_org_core_extension_EventRuntimeInstallAddIn is an interface wrapper for EventRuntimeInstallAddIn type
type _git_golaxy_org_core_extension_EventRuntimeInstallAddIn struct {
	IValue                 interface{}
	WOnRuntimeInstallAddIn func(status extension.RuntimeAddInStatus)
}

func (W _git_golaxy_org_core_extension_EventRuntimeInstallAddIn) OnRuntimeInstallAddIn(status extension.RuntimeAddInStatus) {
	W.WOnRuntimeInstallAddIn(status)
}

// _git_golaxy_org_core_extension_EventRuntimeUninstallAddIn is an interface wrapper for EventRuntimeUninstallAddIn type
type _git_golaxy_org_core_extension_EventRuntimeUninstallAddIn struct {
	IValue                   interface{}
	WOnRuntimeUninstallAddIn func(status extension.RuntimeAddInStatus)
}

func (W _git_golaxy_org_core_extension_EventRuntimeUninstallAddIn) OnRuntimeUninstallAddIn(status extension.RuntimeAddInStatus) {
	W.WOnRuntimeUninstallAddIn(status)
}

// _git_golaxy_org_core_extension_IRuntimeAddInManagerEventTab is an interface wrapper for IRuntimeAddInManagerEventTab type
type _git_golaxy_org_core_extension_IRuntimeAddInManagerEventTab struct {
	IValue                         interface{}
	WEventRuntimeAddInStateChanged func() event.IEvent
	WEventRuntimeInstallAddIn      func() event.IEvent
	WEventRuntimeUninstallAddIn    func() event.IEvent
}

func (W _git_golaxy_org_core_extension_IRuntimeAddInManagerEventTab) EventRuntimeAddInStateChanged() event.IEvent {
	return W.WEventRuntimeAddInStateChanged()
}
func (W _git_golaxy_org_core_extension_IRuntimeAddInManagerEventTab) EventRuntimeInstallAddIn() event.IEvent {
	return W.WEventRuntimeInstallAddIn()
}
func (W _git_golaxy_org_core_extension_IRuntimeAddInManagerEventTab) EventRuntimeUninstallAddIn() event.IEvent {
	return W.WEventRuntimeUninstallAddIn()
}

// _git_golaxy_org_core_extension_RuntimeAddInManager is an interface wrapper for RuntimeAddInManager type
type _git_golaxy_org_core_extension_RuntimeAddInManager struct {
	IValue                         interface{}
	WAddInManager                  func() extension.AddInManager
	WEventRuntimeAddInStateChanged func() event.IEvent
	WEventRuntimeInstallAddIn      func() event.IEvent
	WEventRuntimeUninstallAddIn    func() event.IEvent
	WGetStatusById                 func(id uint64) (extension.AddInStatus, bool)
	WGetStatusByName               func(name string) (extension.AddInStatus, bool)
	WInstall                       func(addInFace iface.FaceAny, name ...string) extension.AddInStatus
	WListStatuses                  func() []extension.AddInStatus
	WUninstall                     func(name string)
}

func (W _git_golaxy_org_core_extension_RuntimeAddInManager) AddInManager() extension.AddInManager {
	return W.WAddInManager()
}
func (W _git_golaxy_org_core_extension_RuntimeAddInManager) EventRuntimeAddInStateChanged() event.IEvent {
	return W.WEventRuntimeAddInStateChanged()
}
func (W _git_golaxy_org_core_extension_RuntimeAddInManager) EventRuntimeInstallAddIn() event.IEvent {
	return W.WEventRuntimeInstallAddIn()
}
func (W _git_golaxy_org_core_extension_RuntimeAddInManager) EventRuntimeUninstallAddIn() event.IEvent {
	return W.WEventRuntimeUninstallAddIn()
}
func (W _git_golaxy_org_core_extension_RuntimeAddInManager) GetStatusById(id uint64) (extension.AddInStatus, bool) {
	return W.WGetStatusById(id)
}
func (W _git_golaxy_org_core_extension_RuntimeAddInManager) GetStatusByName(name string) (extension.AddInStatus, bool) {
	return W.WGetStatusByName(name)
}
func (W _git_golaxy_org_core_extension_RuntimeAddInManager) Install(addInFace iface.FaceAny, name ...string) extension.AddInStatus {
	return W.WInstall(addInFace, name...)
}
func (W _git_golaxy_org_core_extension_RuntimeAddInManager) ListStatuses() []extension.AddInStatus {
	return W.WListStatuses()
}
func (W _git_golaxy_org_core_extension_RuntimeAddInManager) Uninstall(name string) {
	W.WUninstall(name)
}

// _git_golaxy_org_core_extension_RuntimeAddInStatus is an interface wrapper for RuntimeAddInStatus type
type _git_golaxy_org_core_extension_RuntimeAddInStatus struct {
	IValue        interface{}
	WId           func() uint64
	WInstanceFace func() iface.FaceAny
	WName         func() string
	WReflected    func() reflect.Value
	WState        func() extension.AddInState
	WString       func() string
}

func (W _git_golaxy_org_core_extension_RuntimeAddInStatus) Id() uint64 { return W.WId() }
func (W _git_golaxy_org_core_extension_RuntimeAddInStatus) InstanceFace() iface.FaceAny {
	return W.WInstanceFace()
}
func (W _git_golaxy_org_core_extension_RuntimeAddInStatus) Name() string { return W.WName() }
func (W _git_golaxy_org_core_extension_RuntimeAddInStatus) Reflected() reflect.Value {
	return W.WReflected()
}
func (W _git_golaxy_org_core_extension_RuntimeAddInStatus) State() extension.AddInState {
	return W.WState()
}
func (W _git_golaxy_org_core_extension_RuntimeAddInStatus) String() string {
	if W.WString == nil {
		return ""
	}
	return W.WString()
}

// _git_golaxy_org_core_extension_ServiceAddInManager is an interface wrapper for ServiceAddInManager type
type _git_golaxy_org_core_extension_ServiceAddInManager struct {
	IValue           interface{}
	WAddInManager    func() extension.AddInManager
	WGetStatusById   func(id uint64) (extension.AddInStatus, bool)
	WGetStatusByName func(name string) (extension.AddInStatus, bool)
	WInstall         func(addInFace iface.FaceAny, name ...string) extension.AddInStatus
	WListStatuses    func() []extension.AddInStatus
	WUninstall       func(name string)
	WWatchEvent      func(ctx context.Context) <-chan any
}

func (W _git_golaxy_org_core_extension_ServiceAddInManager) AddInManager() extension.AddInManager {
	return W.WAddInManager()
}
func (W _git_golaxy_org_core_extension_ServiceAddInManager) GetStatusById(id uint64) (extension.AddInStatus, bool) {
	return W.WGetStatusById(id)
}
func (W _git_golaxy_org_core_extension_ServiceAddInManager) GetStatusByName(name string) (extension.AddInStatus, bool) {
	return W.WGetStatusByName(name)
}
func (W _git_golaxy_org_core_extension_ServiceAddInManager) Install(addInFace iface.FaceAny, name ...string) extension.AddInStatus {
	return W.WInstall(addInFace, name...)
}
func (W _git_golaxy_org_core_extension_ServiceAddInManager) ListStatuses() []extension.AddInStatus {
	return W.WListStatuses()
}
func (W _git_golaxy_org_core_extension_ServiceAddInManager) Uninstall(name string) {
	W.WUninstall(name)
}
func (W _git_golaxy_org_core_extension_ServiceAddInManager) WatchEvent(ctx context.Context) <-chan any {
	return W.WWatchEvent(ctx)
}

// _git_golaxy_org_core_extension_ServiceAddInStatus is an interface wrapper for ServiceAddInStatus type
type _git_golaxy_org_core_extension_ServiceAddInStatus struct {
	IValue        interface{}
	WId           func() uint64
	WInstanceFace func() iface.FaceAny
	WName         func() string
	WReflected    func() reflect.Value
	WState        func() extension.AddInState
	WString       func() string
	WWaitState    func(state extension.AddInState) async.Future
}

func (W _git_golaxy_org_core_extension_ServiceAddInStatus) Id() uint64 { return W.WId() }
func (W _git_golaxy_org_core_extension_ServiceAddInStatus) InstanceFace() iface.FaceAny {
	return W.WInstanceFace()
}
func (W _git_golaxy_org_core_extension_ServiceAddInStatus) Name() string { return W.WName() }
func (W _git_golaxy_org_core_extension_ServiceAddInStatus) Reflected() reflect.Value {
	return W.WReflected()
}
func (W _git_golaxy_org_core_extension_ServiceAddInStatus) State() extension.AddInState {
	return W.WState()
}
func (W _git_golaxy_org_core_extension_ServiceAddInStatus) String() string {
	if W.WString == nil {
		return ""
	}
	return W.WString()
}
func (W _git_golaxy_org_core_extension_ServiceAddInStatus) WaitState(state extension.AddInState) async.Future {
	return W.WWaitState(state)
}
