// Code generated by 'yaegi extract git.golaxy.org/scaffold/tools/excelc/excelutils'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/scaffold/tools/excelc/excelutils"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/scaffold/tools/excelc/excelutils/excelutils"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AnyToHash":                      reflect.ValueOf(excelutils.AnyToHash),
		"AnyToIndex":                     reflect.ValueOf(excelutils.AnyToIndex),
		"BooleanToIndex":                 reflect.ValueOf(excelutils.BooleanToIndex),
		"BytesToIndex":                   reflect.ValueOf(excelutils.BytesToIndex),
		"DoubleToIndex":                  reflect.ValueOf(excelutils.DoubleToIndex),
		"FloatToIndex":                   reflect.ValueOf(excelutils.FloatToIndex),
		"LoadTableFromBinaryData":        reflect.ValueOf(excelutils.LoadTableFromBinaryData),
		"LoadTableFromBinaryFile":        reflect.ValueOf(excelutils.LoadTableFromBinaryFile),
		"LoadTableFromJsonData":          reflect.ValueOf(excelutils.LoadTableFromJsonData),
		"LoadTableFromJsonFile":          reflect.ValueOf(excelutils.LoadTableFromJsonFile),
		"NewHash":                        reflect.ValueOf(&excelutils.NewHash).Elem(),
		"ProtoMessageFieldNeedHashIndex": reflect.ValueOf(excelutils.ProtoMessageFieldNeedHashIndex),
		"ProtoMessageFieldToIndex":       reflect.ValueOf(excelutils.ProtoMessageFieldToIndex),
		"StringToIndex":                  reflect.ValueOf(excelutils.StringToIndex),
	}
}
