// Code generated by 'yaegi extract git.golaxy.org/framework/addins/dsvc'. DO NOT EDIT.

package fwlib

import (
	"context"
	"git.golaxy.org/core/utils/async"
	"git.golaxy.org/framework/addins/dsvc"
	"git.golaxy.org/framework/net/gap"
	"git.golaxy.org/framework/utils/concurrent"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/addins/dsvc/dsvc"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddIn": reflect.ValueOf(&dsvc.AddIn).Elem(),
		"With":  reflect.ValueOf(&dsvc.With).Elem(),

		// type definitions
		"DistServiceOptions": reflect.ValueOf((*dsvc.DistServiceOptions)(nil)),
		"IDistService":       reflect.ValueOf((*dsvc.IDistService)(nil)),
		"MsgHandler":         reflect.ValueOf((*dsvc.MsgHandler)(nil)),
		"NodeDetails":        reflect.ValueOf((*dsvc.NodeDetails)(nil)),

		// interface wrapper definitions
		"_IDistService": reflect.ValueOf((*_git_golaxy_org_framework_addins_dsvc_IDistService)(nil)),
	}
}

// _git_golaxy_org_framework_addins_dsvc_IDistService is an interface wrapper for IDistService type
type _git_golaxy_org_framework_addins_dsvc_IDistService struct {
	IValue            interface{}
	WBringUp          func()
	WFutureController func() *concurrent.FutureController
	WListen           func(ctx context.Context, handler dsvc.MsgHandler) (async.Future, error)
	WNodeDetails      func() *dsvc.NodeDetails
	WSend             func(dst string, msg gap.Msg) error
}

func (W _git_golaxy_org_framework_addins_dsvc_IDistService) BringUp() { W.WBringUp() }
func (W _git_golaxy_org_framework_addins_dsvc_IDistService) FutureController() *concurrent.FutureController {
	return W.WFutureController()
}
func (W _git_golaxy_org_framework_addins_dsvc_IDistService) Listen(ctx context.Context, handler dsvc.MsgHandler) (async.Future, error) {
	return W.WListen(ctx, handler)
}
func (W _git_golaxy_org_framework_addins_dsvc_IDistService) NodeDetails() *dsvc.NodeDetails {
	return W.WNodeDetails()
}
func (W _git_golaxy_org_framework_addins_dsvc_IDistService) Send(dst string, msg gap.Msg) error {
	return W.WSend(dst, msg)
}
