// Code generated by 'yaegi extract git.golaxy.org/framework/utils/binaryutil'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/framework/utils/binaryutil"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/utils/binaryutil/binaryutil"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BytesPool":             reflect.ValueOf(&binaryutil.BytesPool).Elem(),
		"CloneBytes":            reflect.ValueOf(binaryutil.CloneBytes),
		"EmptyBytes":            reflect.ValueOf(&binaryutil.EmptyBytes).Elem(),
		"ErrInvalidSeekPos":     reflect.ValueOf(&binaryutil.ErrInvalidSeekPos).Elem(),
		"ErrLimitReached":       reflect.ValueOf(&binaryutil.ErrLimitReached).Elem(),
		"NewBigEndianStream":    reflect.ValueOf(binaryutil.NewBigEndianStream),
		"NewByteStream":         reflect.ValueOf(binaryutil.NewByteStream),
		"NewBytes":              reflect.ValueOf(binaryutil.NewBytes),
		"NewBytesWriter":        reflect.ValueOf(binaryutil.NewBytesWriter),
		"NewLimitWriter":        reflect.ValueOf(binaryutil.NewLimitWriter),
		"NewLittleEndianStream": reflect.ValueOf(binaryutil.NewLittleEndianStream),
		"RefBytes":              reflect.ValueOf(binaryutil.RefBytes),
		"SizeofBool":            reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
		"SizeofByte":            reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
		"SizeofBytes":           reflect.ValueOf(binaryutil.SizeofBytes),
		"SizeofBytes128":        reflect.ValueOf(constant.MakeFromLiteral("128", token.INT, 0)),
		"SizeofBytes16":         reflect.ValueOf(constant.MakeFromLiteral("16", token.INT, 0)),
		"SizeofBytes160":        reflect.ValueOf(constant.MakeFromLiteral("160", token.INT, 0)),
		"SizeofBytes256":        reflect.ValueOf(constant.MakeFromLiteral("256", token.INT, 0)),
		"SizeofBytes32":         reflect.ValueOf(constant.MakeFromLiteral("32", token.INT, 0)),
		"SizeofBytes512":        reflect.ValueOf(constant.MakeFromLiteral("512", token.INT, 0)),
		"SizeofBytes64":         reflect.ValueOf(constant.MakeFromLiteral("64", token.INT, 0)),
		"SizeofDouble":          reflect.ValueOf(constant.MakeFromLiteral("8", token.INT, 0)),
		"SizeofFloat":           reflect.ValueOf(constant.MakeFromLiteral("4", token.INT, 0)),
		"SizeofInt16":           reflect.ValueOf(constant.MakeFromLiteral("2", token.INT, 0)),
		"SizeofInt32":           reflect.ValueOf(constant.MakeFromLiteral("4", token.INT, 0)),
		"SizeofInt64":           reflect.ValueOf(constant.MakeFromLiteral("8", token.INT, 0)),
		"SizeofInt8":            reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
		"SizeofString":          reflect.ValueOf(binaryutil.SizeofString),
		"SizeofUint16":          reflect.ValueOf(constant.MakeFromLiteral("2", token.INT, 0)),
		"SizeofUint32":          reflect.ValueOf(constant.MakeFromLiteral("4", token.INT, 0)),
		"SizeofUint64":          reflect.ValueOf(constant.MakeFromLiteral("8", token.INT, 0)),
		"SizeofUint8":           reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
		"SizeofUvarint":         reflect.ValueOf(binaryutil.SizeofUvarint),
		"SizeofVarint":          reflect.ValueOf(binaryutil.SizeofVarint),

		// type definitions
		"ByteStream":  reflect.ValueOf((*binaryutil.ByteStream)(nil)),
		"Bytes":       reflect.ValueOf((*binaryutil.Bytes)(nil)),
		"BytesWriter": reflect.ValueOf((*binaryutil.BytesWriter)(nil)),
		"LimitWriter": reflect.ValueOf((*binaryutil.LimitWriter)(nil)),
	}
}
