// Code generated by 'yaegi extract git.golaxy.org/framework/addins/db/mongodb'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/framework/addins/db/mongodb"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/addins/db/mongodb/mongodb"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddIn": reflect.ValueOf(&mongodb.AddIn).Elem(),
		"DB":    reflect.ValueOf(mongodb.DB),
		"With":  reflect.ValueOf(&mongodb.With).Elem(),

		// type definitions
		"IMongoDB":       reflect.ValueOf((*mongodb.IMongoDB)(nil)),
		"MongoDBOptions": reflect.ValueOf((*mongodb.MongoDBOptions)(nil)),

		// interface wrapper definitions
		"_IMongoDB": reflect.ValueOf((*_git_golaxy_org_framework_addins_db_mongodb_IMongoDB)(nil)),
	}
}

// _git_golaxy_org_framework_addins_db_mongodb_IMongoDB is an interface wrapper for IMongoDB type
type _git_golaxy_org_framework_addins_db_mongodb_IMongoDB struct {
	IValue       interface{}
	WDB          func(tag string) *mongo.Client
	WReflectedDB func(tag string) reflect.Value
}

func (W _git_golaxy_org_framework_addins_db_mongodb_IMongoDB) DB(tag string) *mongo.Client {
	return W.WDB(tag)
}
func (W _git_golaxy_org_framework_addins_db_mongodb_IMongoDB) ReflectedDB(tag string) reflect.Value {
	return W.WReflectedDB(tag)
}
