// Code generated by 'yaegi extract git.golaxy.org/framework/addins/broker/broker_nats'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/framework/addins/broker/broker_nats"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/addins/broker/broker_nats/broker_nats"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddIn": reflect.ValueOf(&broker_nats.AddIn).Elem(),
		"With":  reflect.ValueOf(&broker_nats.With).Elem(),

		// type definitions
		"NatsBrokerOptions": reflect.ValueOf((*broker_nats.NatsBrokerOptions)(nil)),
	}
}
