// Code generated by 'yaegi extract git.golaxy.org/framework/addins/dsync'. DO NOT EDIT.

package fwlib

import (
	"context"
	"git.golaxy.org/core/utils/option"
	"git.golaxy.org/framework/addins/dsync"
	"reflect"
	"time"
)

func init() {
	Symbols["git.golaxy.org/framework/addins/dsync/dsync"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddIn":              reflect.ValueOf(&dsync.AddIn).Elem(),
		"ErrAlreadyAcquired": reflect.ValueOf(&dsync.ErrAlreadyAcquired).Elem(),
		"ErrNotAcquired":     reflect.ValueOf(&dsync.ErrNotAcquired).Elem(),
		"With":               reflect.ValueOf(&dsync.With).Elem(),

		// type definitions
		"DistMutexOptions": reflect.ValueOf((*dsync.DistMutexOptions)(nil)),
		"GenUIDFunc":       reflect.ValueOf((*dsync.GenUIDFunc)(nil)),
		"IDistMutex":       reflect.ValueOf((*dsync.IDistMutex)(nil)),
		"IDistSync":        reflect.ValueOf((*dsync.IDistSync)(nil)),
		"RetryDelayFunc":   reflect.ValueOf((*dsync.RetryDelayFunc)(nil)),

		// interface wrapper definitions
		"_IDistMutex": reflect.ValueOf((*_git_golaxy_org_framework_addins_dsync_IDistMutex)(nil)),
		"_IDistSync":  reflect.ValueOf((*_git_golaxy_org_framework_addins_dsync_IDistSync)(nil)),
	}
}

// _git_golaxy_org_framework_addins_dsync_IDistMutex is an interface wrapper for IDistMutex type
type _git_golaxy_org_framework_addins_dsync_IDistMutex struct {
	IValue   interface{}
	WExtend  func(ctx context.Context) error
	WLock    func(ctx context.Context) error
	WName    func() string
	WTryLock func(ctx context.Context) error
	WUID     func() string
	WUnlock  func(ctx context.Context) error
	WUntil   func() time.Time
}

func (W _git_golaxy_org_framework_addins_dsync_IDistMutex) Extend(ctx context.Context) error {
	return W.WExtend(ctx)
}
func (W _git_golaxy_org_framework_addins_dsync_IDistMutex) Lock(ctx context.Context) error {
	return W.WLock(ctx)
}
func (W _git_golaxy_org_framework_addins_dsync_IDistMutex) Name() string { return W.WName() }
func (W _git_golaxy_org_framework_addins_dsync_IDistMutex) TryLock(ctx context.Context) error {
	return W.WTryLock(ctx)
}
func (W _git_golaxy_org_framework_addins_dsync_IDistMutex) UID() string { return W.WUID() }
func (W _git_golaxy_org_framework_addins_dsync_IDistMutex) Unlock(ctx context.Context) error {
	return W.WUnlock(ctx)
}
func (W _git_golaxy_org_framework_addins_dsync_IDistMutex) Until() time.Time { return W.WUntil() }

// _git_golaxy_org_framework_addins_dsync_IDistSync is an interface wrapper for IDistSync type
type _git_golaxy_org_framework_addins_dsync_IDistSync struct {
	IValue     interface{}
	WNewMutex  func(name string, settings ...option.Setting[dsync.DistMutexOptions]) dsync.IDistMutex
	WSeparator func() string
}

func (W _git_golaxy_org_framework_addins_dsync_IDistSync) NewMutex(name string, settings ...option.Setting[dsync.DistMutexOptions]) dsync.IDistMutex {
	return W.WNewMutex(name, settings...)
}
func (W _git_golaxy_org_framework_addins_dsync_IDistSync) Separator() string { return W.WSeparator() }
