// Code generated by 'yaegi extract git.golaxy.org/framework/addins/rpc/rpcli'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/framework/addins/rpc/rpcli"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/addins/rpc/rpcli/rpcli"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BuildRPCli":                      reflect.ValueOf(rpcli.BuildRPCli),
		"ErrMethodNotFound":               reflect.ValueOf(&rpcli.ErrMethodNotFound).Elem(),
		"ErrMethodParameterCountMismatch": reflect.ValueOf(&rpcli.ErrMethodParameterCountMismatch).Elem(),
		"ErrMethodParameterTypeMismatch":  reflect.ValueOf(&rpcli.ErrMethodParameterTypeMismatch).Elem(),
		"ErrScriptNotFound":               reflect.ValueOf(&rpcli.ErrScriptNotFound).Elem(),

		// type definitions
		"IScript":        reflect.ValueOf((*rpcli.IScript)(nil)),
		"RPCli":          reflect.ValueOf((*rpcli.RPCli)(nil)),
		"RPCliCreator":   reflect.ValueOf((*rpcli.RPCliCreator)(nil)),
		"ScriptBehavior": reflect.ValueOf((*rpcli.ScriptBehavior)(nil)),

		// interface wrapper definitions
		"_IScript": reflect.ValueOf((*_git_golaxy_org_framework_addins_rpc_rpcli_IScript)(nil)),
	}
}

// _git_golaxy_org_framework_addins_rpc_rpcli_IScript is an interface wrapper for IScript type
type _git_golaxy_org_framework_addins_rpc_rpcli_IScript struct {
	IValue     interface{}
	WCli       func() *rpcli.RPCli
	WName      func() string
	WReflected func() reflect.Value
}

func (W _git_golaxy_org_framework_addins_rpc_rpcli_IScript) Cli() *rpcli.RPCli { return W.WCli() }
func (W _git_golaxy_org_framework_addins_rpc_rpcli_IScript) Name() string      { return W.WName() }
func (W _git_golaxy_org_framework_addins_rpc_rpcli_IScript) Reflected() reflect.Value {
	return W.WReflected()
}
