// Code generated by 'yaegi extract git.golaxy.org/core/utils/assertion'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/core/utils/assertion"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/core/utils/assertion/assertion"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Inject":   reflect.ValueOf(assertion.Inject),
		"InjectRV": reflect.ValueOf(assertion.InjectRV),
	}
}
