// Code generated by 'yaegi extract git.golaxy.org/core/define'. DO NOT EDIT.

package fwlib

import (
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/core/define/define"] = map[string]reflect.Value{}
}
