// Code generated by 'yaegi extract git.golaxy.org/framework/addins/dsync/dsync_redis'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/framework/addins/dsync/dsync_redis"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/addins/dsync/dsync_redis/dsync_redis"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddIn": reflect.ValueOf(&dsync_redis.AddIn).Elem(),
		"With":  reflect.ValueOf(&dsync_redis.With).Elem(),

		// type definitions
		"RedisSyncOptions": reflect.ValueOf((*dsync_redis.RedisSyncOptions)(nil)),
	}
}
