// Code generated by 'yaegi extract git.golaxy.org/core/service'. DO NOT EDIT.

package fwlib

import (
	"context"
	"git.golaxy.org/core/ec"
	"git.golaxy.org/core/ec/pt"
	"git.golaxy.org/core/extension"
	"git.golaxy.org/core/service"
	"git.golaxy.org/core/utils/async"
	"git.golaxy.org/core/utils/corectx"
	"git.golaxy.org/core/utils/generic"
	"git.golaxy.org/core/utils/iface"
	"git.golaxy.org/core/utils/uid"
	"reflect"
	"time"
)

func init() {
	Symbols["git.golaxy.org/core/service/service"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Current":                          reflect.ValueOf(service.Current),
		"ErrContext":                       reflect.ValueOf(&service.ErrContext).Elem(),
		"ErrEntityManager":                 reflect.ValueOf(&service.ErrEntityManager).Elem(),
		"NewContext":                       reflect.ValueOf(service.NewContext),
		"RunningEvent_AddInActivated":      reflect.ValueOf(service.RunningEvent_AddInActivated),
		"RunningEvent_AddInActivating":     reflect.ValueOf(service.RunningEvent_AddInActivating),
		"RunningEvent_AddInDeactivated":    reflect.ValueOf(service.RunningEvent_AddInDeactivated),
		"RunningEvent_AddInDeactivating":   reflect.ValueOf(service.RunningEvent_AddInDeactivating),
		"RunningEvent_Birth":               reflect.ValueOf(service.RunningEvent_Birth),
		"RunningEvent_ComponentPTDeclared": reflect.ValueOf(service.RunningEvent_ComponentPTDeclared),
		"RunningEvent_EntityDeregistered":  reflect.ValueOf(service.RunningEvent_EntityDeregistered),
		"RunningEvent_EntityPTDeclared":    reflect.ValueOf(service.RunningEvent_EntityPTDeclared),
		"RunningEvent_EntityRegistered":    reflect.ValueOf(service.RunningEvent_EntityRegistered),
		"RunningEvent_Heartbeat":           reflect.ValueOf(service.RunningEvent_Heartbeat),
		"RunningEvent_Started":             reflect.ValueOf(service.RunningEvent_Started),
		"RunningEvent_Starting":            reflect.ValueOf(service.RunningEvent_Starting),
		"RunningEvent_Terminated":          reflect.ValueOf(service.RunningEvent_Terminated),
		"RunningEvent_Terminating":         reflect.ValueOf(service.RunningEvent_Terminating),
		"UnsafeContext":                    reflect.ValueOf(service.UnsafeContext),
		"UnsafeNewContext":                 reflect.ValueOf(service.UnsafeNewContext),
		"With":                             reflect.ValueOf(&service.With).Elem(),

		// type definitions
		"Caller":          reflect.ValueOf((*service.Caller)(nil)),
		"Context":         reflect.ValueOf((*service.Context)(nil)),
		"ContextBehavior": reflect.ValueOf((*service.ContextBehavior)(nil)),
		"ContextOptions":  reflect.ValueOf((*service.ContextOptions)(nil)),
		"EntityManager":   reflect.ValueOf((*service.EntityManager)(nil)),
		"RunningEvent":    reflect.ValueOf((*service.RunningEvent)(nil)),
		"RunningEventCB":  reflect.ValueOf((*service.RunningEventCB)(nil)),

		// interface wrapper definitions
		"_Caller":        reflect.ValueOf((*_git_golaxy_org_core_service_Caller)(nil)),
		"_Context":       reflect.ValueOf((*_git_golaxy_org_core_service_Context)(nil)),
		"_EntityManager": reflect.ValueOf((*_git_golaxy_org_core_service_EntityManager)(nil)),
	}
}

// _git_golaxy_org_core_service_Caller is an interface wrapper for Caller type
type _git_golaxy_org_core_service_Caller struct {
	IValue                 interface{}
	WCallAsync             func(entityId uid.Id, fun generic.FuncVar1[ec.Entity, any, async.Result], args ...any) async.Future
	WCallDelegateAsync     func(entityId uid.Id, fun generic.DelegateVar1[ec.Entity, any, async.Result], args ...any) async.Future
	WCallDelegateVoidAsync func(entityId uid.Id, fun generic.DelegateVoidVar1[ec.Entity, any], args ...any) async.Future
	WCallVoidAsync         func(entityId uid.Id, fun generic.ActionVar1[ec.Entity, any], args ...any) async.Future
}

func (W _git_golaxy_org_core_service_Caller) CallAsync(entityId uid.Id, fun generic.FuncVar1[ec.Entity, any, async.Result], args ...any) async.Future {
	return W.WCallAsync(entityId, fun, args...)
}
func (W _git_golaxy_org_core_service_Caller) CallDelegateAsync(entityId uid.Id, fun generic.DelegateVar1[ec.Entity, any, async.Result], args ...any) async.Future {
	return W.WCallDelegateAsync(entityId, fun, args...)
}
func (W _git_golaxy_org_core_service_Caller) CallDelegateVoidAsync(entityId uid.Id, fun generic.DelegateVoidVar1[ec.Entity, any], args ...any) async.Future {
	return W.WCallDelegateVoidAsync(entityId, fun, args...)
}
func (W _git_golaxy_org_core_service_Caller) CallVoidAsync(entityId uid.Id, fun generic.ActionVar1[ec.Entity, any], args ...any) async.Future {
	return W.WCallVoidAsync(entityId, fun, args...)
}

// _git_golaxy_org_core_service_Context is an interface wrapper for Context type
type _git_golaxy_org_core_service_Context struct {
	IValue                 interface{}
	WAddInManager          func() extension.AddInManager
	WAutoRecover           func() bool
	WCallAsync             func(entityId uid.Id, fun generic.FuncVar1[ec.Entity, any, async.Result], args ...any) async.Future
	WCallDelegateAsync     func(entityId uid.Id, fun generic.DelegateVar1[ec.Entity, any, async.Result], args ...any) async.Future
	WCallDelegateVoidAsync func(entityId uid.Id, fun generic.DelegateVoidVar1[ec.Entity, any], args ...any) async.Future
	WCallVoidAsync         func(entityId uid.Id, fun generic.ActionVar1[ec.Entity, any], args ...any) async.Future
	WDeadline              func() (deadline time.Time, ok bool)
	WDone                  func() <-chan struct{}
	WEntityLib             func() pt.EntityLib
	WEntityManager         func() service.EntityManager
	WErr                   func() error
	WId                    func() uid.Id
	WInstanceFaceCache     func() iface.Cache
	WName                  func() string
	WParentContext         func() context.Context
	WReflected             func() reflect.Value
	WReportError           func() chan error
	WString                func() string
	WTerminate             func() async.Future
	WTerminated            func() async.Future
	WValue                 func(key any) any
	WWaitGroup             func() corectx.WaitGroup
}

func (W _git_golaxy_org_core_service_Context) AddInManager() extension.AddInManager {
	return W.WAddInManager()
}
func (W _git_golaxy_org_core_service_Context) AutoRecover() bool { return W.WAutoRecover() }
func (W _git_golaxy_org_core_service_Context) CallAsync(entityId uid.Id, fun generic.FuncVar1[ec.Entity, any, async.Result], args ...any) async.Future {
	return W.WCallAsync(entityId, fun, args...)
}
func (W _git_golaxy_org_core_service_Context) CallDelegateAsync(entityId uid.Id, fun generic.DelegateVar1[ec.Entity, any, async.Result], args ...any) async.Future {
	return W.WCallDelegateAsync(entityId, fun, args...)
}
func (W _git_golaxy_org_core_service_Context) CallDelegateVoidAsync(entityId uid.Id, fun generic.DelegateVoidVar1[ec.Entity, any], args ...any) async.Future {
	return W.WCallDelegateVoidAsync(entityId, fun, args...)
}
func (W _git_golaxy_org_core_service_Context) CallVoidAsync(entityId uid.Id, fun generic.ActionVar1[ec.Entity, any], args ...any) async.Future {
	return W.WCallVoidAsync(entityId, fun, args...)
}
func (W _git_golaxy_org_core_service_Context) Deadline() (deadline time.Time, ok bool) {
	return W.WDeadline()
}
func (W _git_golaxy_org_core_service_Context) Done() <-chan struct{}   { return W.WDone() }
func (W _git_golaxy_org_core_service_Context) EntityLib() pt.EntityLib { return W.WEntityLib() }
func (W _git_golaxy_org_core_service_Context) EntityManager() service.EntityManager {
	return W.WEntityManager()
}
func (W _git_golaxy_org_core_service_Context) Err() error { return W.WErr() }
func (W _git_golaxy_org_core_service_Context) Id() uid.Id { return W.WId() }
func (W _git_golaxy_org_core_service_Context) InstanceFaceCache() iface.Cache {
	return W.WInstanceFaceCache()
}
func (W _git_golaxy_org_core_service_Context) Name() string { return W.WName() }
func (W _git_golaxy_org_core_service_Context) ParentContext() context.Context {
	return W.WParentContext()
}
func (W _git_golaxy_org_core_service_Context) Reflected() reflect.Value { return W.WReflected() }
func (W _git_golaxy_org_core_service_Context) ReportError() chan error  { return W.WReportError() }
func (W _git_golaxy_org_core_service_Context) String() string {
	if W.WString == nil {
		return ""
	}
	return W.WString()
}
func (W _git_golaxy_org_core_service_Context) Terminate() async.Future      { return W.WTerminate() }
func (W _git_golaxy_org_core_service_Context) Terminated() async.Future     { return W.WTerminated() }
func (W _git_golaxy_org_core_service_Context) Value(key any) any            { return W.WValue(key) }
func (W _git_golaxy_org_core_service_Context) WaitGroup() corectx.WaitGroup { return W.WWaitGroup() }

// _git_golaxy_org_core_service_EntityManager is an interface wrapper for EntityManager type
type _git_golaxy_org_core_service_EntityManager struct {
	IValue          interface{}
	WGetEntity      func(id uid.Id) (ec.ConcurrentEntity, bool)
	WGetOrAddEntity func(entity ec.ConcurrentEntity) (ec.ConcurrentEntity, bool, error)
	WRemoveEntity   func(id uid.Id)
}

func (W _git_golaxy_org_core_service_EntityManager) GetEntity(id uid.Id) (ec.ConcurrentEntity, bool) {
	return W.WGetEntity(id)
}
func (W _git_golaxy_org_core_service_EntityManager) GetOrAddEntity(entity ec.ConcurrentEntity) (ec.ConcurrentEntity, bool, error) {
	return W.WGetOrAddEntity(entity)
}
func (W _git_golaxy_org_core_service_EntityManager) RemoveEntity(id uid.Id) { W.WRemoveEntity(id) }
