// Code generated by 'yaegi extract git.golaxy.org/framework/net/gap/codec'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/framework/net/gap/codec"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/net/gap/codec/codec"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ErrDecode":  reflect.ValueOf(&codec.ErrDecode).Elem(),
		"ErrEncode":  reflect.ValueOf(&codec.ErrEncode).Elem(),
		"NewDecoder": reflect.ValueOf(codec.NewDecoder),
		"NewEncoder": reflect.ValueOf(codec.NewEncoder),

		// type definitions
		"Decoder": reflect.ValueOf((*codec.Decoder)(nil)),
		"Encoder": reflect.ValueOf((*codec.Encoder)(nil)),
	}
}
