// Code generated by 'yaegi extract git.golaxy.org/core/ec/pt'. DO NOT EDIT.

package fwlib

import (
	"context"
	"git.golaxy.org/core/ec"
	"git.golaxy.org/core/ec/pt"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/core/ec/pt/pt"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DefaultComponentLib":    reflect.ValueOf(pt.DefaultComponentLib),
		"ErrPt":                  reflect.ValueOf(&pt.ErrPt).Elem(),
		"For":                    reflect.ValueOf(pt.For),
		"NewComponentDescriptor": reflect.ValueOf(pt.NewComponentDescriptor),
		"NewComponentLib":        reflect.ValueOf(pt.NewComponentLib),
		"NewEntityDescriptor":    reflect.ValueOf(pt.NewEntityDescriptor),
		"NewEntityLib":           reflect.ValueOf(pt.NewEntityLib),

		// type definitions
		"ComponentDescriptor": reflect.ValueOf((*pt.ComponentDescriptor)(nil)),
		"ComponentLib":        reflect.ValueOf((*pt.ComponentLib)(nil)),
		"EntityDescriptor":    reflect.ValueOf((*pt.EntityDescriptor)(nil)),
		"EntityLib":           reflect.ValueOf((*pt.EntityLib)(nil)),
		"EntityPTProvider":    reflect.ValueOf((*pt.EntityPTProvider)(nil)),

		// interface wrapper definitions
		"_ComponentLib":     reflect.ValueOf((*_git_golaxy_org_core_ec_pt_ComponentLib)(nil)),
		"_EntityLib":        reflect.ValueOf((*_git_golaxy_org_core_ec_pt_EntityLib)(nil)),
		"_EntityPTProvider": reflect.ValueOf((*_git_golaxy_org_core_ec_pt_EntityPTProvider)(nil)),
	}
}

// _git_golaxy_org_core_ec_pt_ComponentLib is an interface wrapper for ComponentLib type
type _git_golaxy_org_core_ec_pt_ComponentLib struct {
	IValue   interface{}
	WDeclare func(comp any) ec.ComponentPT
	WGet     func(prototype string) (ec.ComponentPT, bool)
	WList    func() []ec.ComponentPT
	WWatch   func(ctx context.Context) <-chan ec.ComponentPT
}

func (W _git_golaxy_org_core_ec_pt_ComponentLib) Declare(comp any) ec.ComponentPT {
	return W.WDeclare(comp)
}
func (W _git_golaxy_org_core_ec_pt_ComponentLib) Get(prototype string) (ec.ComponentPT, bool) {
	return W.WGet(prototype)
}
func (W _git_golaxy_org_core_ec_pt_ComponentLib) List() []ec.ComponentPT { return W.WList() }
func (W _git_golaxy_org_core_ec_pt_ComponentLib) Watch(ctx context.Context) <-chan ec.ComponentPT {
	return W.WWatch(ctx)
}

// _git_golaxy_org_core_ec_pt_EntityLib is an interface wrapper for EntityLib type
type _git_golaxy_org_core_ec_pt_EntityLib struct {
	IValue        interface{}
	WComponentLib func() pt.ComponentLib
	WDeclare      func(prototype any, comps ...any) ec.EntityPT
	WEntityLib    func() pt.EntityLib
	WGet          func(prototype string) (ec.EntityPT, bool)
	WList         func() []ec.EntityPT
	WWatch        func(ctx context.Context) <-chan ec.EntityPT
}

func (W _git_golaxy_org_core_ec_pt_EntityLib) ComponentLib() pt.ComponentLib {
	return W.WComponentLib()
}
func (W _git_golaxy_org_core_ec_pt_EntityLib) Declare(prototype any, comps ...any) ec.EntityPT {
	return W.WDeclare(prototype, comps...)
}
func (W _git_golaxy_org_core_ec_pt_EntityLib) EntityLib() pt.EntityLib { return W.WEntityLib() }
func (W _git_golaxy_org_core_ec_pt_EntityLib) Get(prototype string) (ec.EntityPT, bool) {
	return W.WGet(prototype)
}
func (W _git_golaxy_org_core_ec_pt_EntityLib) List() []ec.EntityPT { return W.WList() }
func (W _git_golaxy_org_core_ec_pt_EntityLib) Watch(ctx context.Context) <-chan ec.EntityPT {
	return W.WWatch(ctx)
}

// _git_golaxy_org_core_ec_pt_EntityPTProvider is an interface wrapper for EntityPTProvider type
type _git_golaxy_org_core_ec_pt_EntityPTProvider struct {
	IValue     interface{}
	WEntityLib func() pt.EntityLib
}

func (W _git_golaxy_org_core_ec_pt_EntityPTProvider) EntityLib() pt.EntityLib { return W.WEntityLib() }
