// Code generated by 'yaegi extract git.golaxy.org/core/utils/generic'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/core/utils/generic"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/core/utils/generic/generic"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"FuncError": reflect.ValueOf(generic.FuncError),

		// type definitions
		"Action0":               reflect.ValueOf((*generic.Action0)(nil)),
		"Barrier":               reflect.ValueOf((*generic.Barrier)(nil)),
		"Bits16":                reflect.ValueOf((*generic.Bits16)(nil)),
		"Bits32":                reflect.ValueOf((*generic.Bits32)(nil)),
		"Bits64":                reflect.ValueOf((*generic.Bits64)(nil)),
		"Bits8":                 reflect.ValueOf((*generic.Bits8)(nil)),
		"DelegateVoid0":         reflect.ValueOf((*generic.DelegateVoid0)(nil)),
		"ReentrancyGuardBits16": reflect.ValueOf((*generic.ReentrancyGuardBits16)(nil)),
		"ReentrancyGuardBits32": reflect.ValueOf((*generic.ReentrancyGuardBits32)(nil)),
		"ReentrancyGuardBits64": reflect.ValueOf((*generic.ReentrancyGuardBits64)(nil)),
		"ReentrancyGuardBits8":  reflect.ValueOf((*generic.ReentrancyGuardBits8)(nil)),
	}
}
