// Code generated by 'yaegi extract git.golaxy.org/core/event'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/core/event"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/core/event/event"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DeclareEventId":              reflect.ValueOf(event.DeclareEventId),
		"DeclareEventTabId":           reflect.ValueOf(event.DeclareEventTabId),
		"ErrArgs":                     reflect.ValueOf(&event.ErrArgs).Elem(),
		"ErrEvent":                    reflect.ValueOf(&event.ErrEvent).Elem(),
		"EventRecursionLimit":         reflect.ValueOf(&event.EventRecursionLimit).Elem(),
		"EventRecursion_Allow":        reflect.ValueOf(event.EventRecursion_Allow),
		"EventRecursion_Disallow":     reflect.ValueOf(event.EventRecursion_Disallow),
		"EventRecursion_Discard":      reflect.ValueOf(event.EventRecursion_Discard),
		"EventRecursion_ReceiveOnce":  reflect.ValueOf(event.EventRecursion_ReceiveOnce),
		"EventRecursion_SkipReceived": reflect.ValueOf(event.EventRecursion_SkipReceived),
		"GenEventId":                  reflect.ValueOf(event.GenEventId),
		"GenEventTabId":               reflect.ValueOf(event.GenEventTabId),
		"Panicf":                      reflect.ValueOf(event.Panicf),
		"SplitEventId":                reflect.ValueOf(event.SplitEventId),
		"Unbind":                      reflect.ValueOf(event.Unbind),
		"UnbindHandles":               reflect.ValueOf(event.UnbindHandles),
		"UnsafeEvent":                 reflect.ValueOf(event.UnsafeEvent),

		// type definitions
		"Cache":           reflect.ValueOf((*event.Cache)(nil)),
		"CombineEventTab": reflect.ValueOf((*event.CombineEventTab)(nil)),
		"Event":           reflect.ValueOf((*event.Event)(nil)),
		"EventRecursion":  reflect.ValueOf((*event.EventRecursion)(nil)),
		"Handle":          reflect.ValueOf((*event.Handle)(nil)),
		"IEvent":          reflect.ValueOf((*event.IEvent)(nil)),
		"IEventCtrl":      reflect.ValueOf((*event.IEventCtrl)(nil)),
		"IEventTab":       reflect.ValueOf((*event.IEventTab)(nil)),
		"ManagedHandles":  reflect.ValueOf((*event.ManagedHandles)(nil)),

		// interface wrapper definitions
		"_IEvent":     reflect.ValueOf((*_git_golaxy_org_core_event_IEvent)(nil)),
		"_IEventCtrl": reflect.ValueOf((*_git_golaxy_org_core_event_IEventCtrl)(nil)),
		"_IEventTab":  reflect.ValueOf((*_git_golaxy_org_core_event_IEventTab)(nil)),
	}
}

// _git_golaxy_org_core_event_IEvent is an interface wrapper for IEvent type
type _git_golaxy_org_core_event_IEvent struct {
	IValue interface{}
}

// _git_golaxy_org_core_event_IEventCtrl is an interface wrapper for IEventCtrl type
type _git_golaxy_org_core_event_IEventCtrl struct {
	IValue            interface{}
	WSetEnabled       func(b bool)
	WSetPanicHandling func(autoRecover bool, reportError chan error)
	WSetRecursion     func(recursion event.EventRecursion)
	WUnbindAll        func()
}

func (W _git_golaxy_org_core_event_IEventCtrl) SetEnabled(b bool) { W.WSetEnabled(b) }
func (W _git_golaxy_org_core_event_IEventCtrl) SetPanicHandling(autoRecover bool, reportError chan error) {
	W.WSetPanicHandling(autoRecover, reportError)
}
func (W _git_golaxy_org_core_event_IEventCtrl) SetRecursion(recursion event.EventRecursion) {
	W.WSetRecursion(recursion)
}
func (W _git_golaxy_org_core_event_IEventCtrl) UnbindAll() { W.WUnbindAll() }

// _git_golaxy_org_core_event_IEventTab is an interface wrapper for IEventTab type
type _git_golaxy_org_core_event_IEventTab struct {
	IValue interface{}
	WCtrl  func() event.IEventCtrl
	WEvent func(id uint64) event.IEvent
}

func (W _git_golaxy_org_core_event_IEventTab) Ctrl() event.IEventCtrl       { return W.WCtrl() }
func (W _git_golaxy_org_core_event_IEventTab) Event(id uint64) event.IEvent { return W.WEvent(id) }
