// Code generated by 'yaegi extract git.golaxy.org/core/runtime'. DO NOT EDIT.

package fwlib

import (
	"context"
	"git.golaxy.org/core/ec"
	"git.golaxy.org/core/event"
	"git.golaxy.org/core/extension"
	"git.golaxy.org/core/runtime"
	"git.golaxy.org/core/utils/async"
	"git.golaxy.org/core/utils/corectx"
	"git.golaxy.org/core/utils/generic"
	"git.golaxy.org/core/utils/iface"
	"git.golaxy.org/core/utils/uid"
	"reflect"
	"time"
)

func init() {
	Symbols["git.golaxy.org/core/runtime/runtime"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BindEventAddInStateChanged":                           reflect.ValueOf(runtime.BindEventAddInStateChanged),
		"BindEventContextRunningEvent":                         reflect.ValueOf(runtime.BindEventContextRunningEvent),
		"BindEventEntityManagerAddEntity":                      reflect.ValueOf(runtime.BindEventEntityManagerAddEntity),
		"BindEventEntityManagerEntityAddComponents":            reflect.ValueOf(runtime.BindEventEntityManagerEntityAddComponents),
		"BindEventEntityManagerEntityComponentEnableChanged":   reflect.ValueOf(runtime.BindEventEntityManagerEntityComponentEnableChanged),
		"BindEventEntityManagerEntityFirstTouchComponent":      reflect.ValueOf(runtime.BindEventEntityManagerEntityFirstTouchComponent),
		"BindEventEntityManagerEntityRemoveComponent":          reflect.ValueOf(runtime.BindEventEntityManagerEntityRemoveComponent),
		"BindEventEntityManagerRemoveEntity":                   reflect.ValueOf(runtime.BindEventEntityManagerRemoveEntity),
		"BindEventEntityTreeAddNode":                           reflect.ValueOf(runtime.BindEventEntityTreeAddNode),
		"BindEventEntityTreeMoveNode":                          reflect.ValueOf(runtime.BindEventEntityTreeMoveNode),
		"BindEventEntityTreeRemoveNode":                        reflect.ValueOf(runtime.BindEventEntityTreeRemoveNode),
		"BindEventInstallAddIn":                                reflect.ValueOf(runtime.BindEventInstallAddIn),
		"BindEventUninstallAddIn":                              reflect.ValueOf(runtime.BindEventUninstallAddIn),
		"Concurrent":                                           reflect.ValueOf(runtime.Concurrent),
		"Current":                                              reflect.ValueOf(runtime.Current),
		"ErrBlockingWaitInRuntime":                             reflect.ValueOf(&runtime.ErrBlockingWaitInRuntime).Elem(),
		"ErrContext":                                           reflect.ValueOf(&runtime.ErrContext).Elem(),
		"ErrEntityManager":                                     reflect.ValueOf(&runtime.ErrEntityManager).Elem(),
		"ErrEntityTree":                                        reflect.ValueOf(&runtime.ErrEntityTree).Elem(),
		"ErrFrame":                                             reflect.ValueOf(&runtime.ErrFrame).Elem(),
		"ErrRuntimeSelfWait":                                   reflect.ValueOf(&runtime.ErrRuntimeSelfWait).Elem(),
		"EventAddInStateChangedID":                             reflect.ValueOf(&runtime.EventAddInStateChangedID).Elem(),
		"EventContextRunningEventID":                           reflect.ValueOf(&runtime.EventContextRunningEventID).Elem(),
		"EventEntityManagerAddEntityID":                        reflect.ValueOf(&runtime.EventEntityManagerAddEntityID).Elem(),
		"EventEntityManagerEntityAddComponentsID":              reflect.ValueOf(&runtime.EventEntityManagerEntityAddComponentsID).Elem(),
		"EventEntityManagerEntityComponentEnableChangedID":     reflect.ValueOf(&runtime.EventEntityManagerEntityComponentEnableChangedID).Elem(),
		"EventEntityManagerEntityFirstTouchComponentID":        reflect.ValueOf(&runtime.EventEntityManagerEntityFirstTouchComponentID).Elem(),
		"EventEntityManagerEntityRemoveComponentID":            reflect.ValueOf(&runtime.EventEntityManagerEntityRemoveComponentID).Elem(),
		"EventEntityManagerRemoveEntityID":                     reflect.ValueOf(&runtime.EventEntityManagerRemoveEntityID).Elem(),
		"EventEntityTreeAddNodeID":                             reflect.ValueOf(&runtime.EventEntityTreeAddNodeID).Elem(),
		"EventEntityTreeMoveNodeID":                            reflect.ValueOf(&runtime.EventEntityTreeMoveNodeID).Elem(),
		"EventEntityTreeRemoveNodeID":                          reflect.ValueOf(&runtime.EventEntityTreeRemoveNodeID).Elem(),
		"EventInstallAddInID":                                  reflect.ValueOf(&runtime.EventInstallAddInID).Elem(),
		"EventUninstallAddInID":                                reflect.ValueOf(&runtime.EventUninstallAddInID).Elem(),
		"ForestNodeID":                                         reflect.ValueOf(&runtime.ForestNodeID).Elem(),
		"HandleEventAddInStateChanged":                         reflect.ValueOf(runtime.HandleEventAddInStateChanged),
		"HandleEventContextRunningEvent":                       reflect.ValueOf(runtime.HandleEventContextRunningEvent),
		"HandleEventEntityManagerAddEntity":                    reflect.ValueOf(runtime.HandleEventEntityManagerAddEntity),
		"HandleEventEntityManagerEntityAddComponents":          reflect.ValueOf(runtime.HandleEventEntityManagerEntityAddComponents),
		"HandleEventEntityManagerEntityComponentEnableChanged": reflect.ValueOf(runtime.HandleEventEntityManagerEntityComponentEnableChanged),
		"HandleEventEntityManagerEntityFirstTouchComponent":    reflect.ValueOf(runtime.HandleEventEntityManagerEntityFirstTouchComponent),
		"HandleEventEntityManagerEntityRemoveComponent":        reflect.ValueOf(runtime.HandleEventEntityManagerEntityRemoveComponent),
		"HandleEventEntityManagerRemoveEntity":                 reflect.ValueOf(runtime.HandleEventEntityManagerRemoveEntity),
		"HandleEventEntityTreeAddNode":                         reflect.ValueOf(runtime.HandleEventEntityTreeAddNode),
		"HandleEventEntityTreeMoveNode":                        reflect.ValueOf(runtime.HandleEventEntityTreeMoveNode),
		"HandleEventEntityTreeRemoveNode":                      reflect.ValueOf(runtime.HandleEventEntityTreeRemoveNode),
		"HandleEventInstallAddIn":                              reflect.ValueOf(runtime.HandleEventInstallAddIn),
		"HandleEventUninstallAddIn":                            reflect.ValueOf(runtime.HandleEventUninstallAddIn),
		"NewAddInManager":                                      reflect.ValueOf(runtime.NewAddInManager),
		"NewContext":                                           reflect.ValueOf(runtime.NewContext),
		"RunningEvent_AddInActivated":                          reflect.ValueOf(runtime.RunningEvent_AddInActivated),
		"RunningEvent_AddInActivating":                         reflect.ValueOf(runtime.RunningEvent_AddInActivating),
		"RunningEvent_AddInActivationAborted":                  reflect.ValueOf(runtime.RunningEvent_AddInActivationAborted),
		"RunningEvent_AddInDeactivated":                        reflect.ValueOf(runtime.RunningEvent_AddInDeactivated),
		"RunningEvent_AddInDeactivating":                       reflect.ValueOf(runtime.RunningEvent_AddInDeactivating),
		"RunningEvent_Birth":                                   reflect.ValueOf(runtime.RunningEvent_Birth),
		"RunningEvent_EntityActivated":                         reflect.ValueOf(runtime.RunningEvent_EntityActivated),
		"RunningEvent_EntityActivating":                        reflect.ValueOf(runtime.RunningEvent_EntityActivating),
		"RunningEvent_EntityActivationAborted":                 reflect.ValueOf(runtime.RunningEvent_EntityActivationAborted),
		"RunningEvent_EntityComponentDeactivated":              reflect.ValueOf(runtime.RunningEvent_EntityComponentDeactivated),
		"RunningEvent_EntityComponentDeactivating":             reflect.ValueOf(runtime.RunningEvent_EntityComponentDeactivating),
		"RunningEvent_EntityComponentDeactivationAborted":      reflect.ValueOf(runtime.RunningEvent_EntityComponentDeactivationAborted),
		"RunningEvent_EntityComponentsActivated":               reflect.ValueOf(runtime.RunningEvent_EntityComponentsActivated),
		"RunningEvent_EntityComponentsActivating":              reflect.ValueOf(runtime.RunningEvent_EntityComponentsActivating),
		"RunningEvent_EntityComponentsActivationAborted":       reflect.ValueOf(runtime.RunningEvent_EntityComponentsActivationAborted),
		"RunningEvent_EntityDeactivated":                       reflect.ValueOf(runtime.RunningEvent_EntityDeactivated),
		"RunningEvent_EntityDeactivating":                      reflect.ValueOf(runtime.RunningEvent_EntityDeactivating),
		"RunningEvent_FrameLoopBegin":                          reflect.ValueOf(runtime.RunningEvent_FrameLoopBegin),
		"RunningEvent_FrameLoopEnd":                            reflect.ValueOf(runtime.RunningEvent_FrameLoopEnd),
		"RunningEvent_FrameUpdateBegin":                        reflect.ValueOf(runtime.RunningEvent_FrameUpdateBegin),
		"RunningEvent_FrameUpdateEnd":                          reflect.ValueOf(runtime.RunningEvent_FrameUpdateEnd),
		"RunningEvent_RunCallBegin":                            reflect.ValueOf(runtime.RunningEvent_RunCallBegin),
		"RunningEvent_RunCallEnd":                              reflect.ValueOf(runtime.RunningEvent_RunCallEnd),
		"RunningEvent_RunGCBegin":                              reflect.ValueOf(runtime.RunningEvent_RunGCBegin),
		"RunningEvent_RunGCEnd":                                reflect.ValueOf(runtime.RunningEvent_RunGCEnd),
		"RunningEvent_Started":                                 reflect.ValueOf(runtime.RunningEvent_Started),
		"RunningEvent_Starting":                                reflect.ValueOf(runtime.RunningEvent_Starting),
		"RunningEvent_Terminated":                              reflect.ValueOf(runtime.RunningEvent_Terminated),
		"RunningEvent_Terminating":                             reflect.ValueOf(runtime.RunningEvent_Terminating),
		"UnsafeAddInManager":                                   reflect.ValueOf(runtime.UnsafeAddInManager),
		"UnsafeAddInStatus":                                    reflect.ValueOf(runtime.UnsafeAddInStatus),
		"UnsafeConcurrentContext":                              reflect.ValueOf(runtime.UnsafeConcurrentContext),
		"UnsafeContext":                                        reflect.ValueOf(runtime.UnsafeContext),
		"UnsafeNewContext":                                     reflect.ValueOf(runtime.UnsafeNewContext),
		"With":                                                 reflect.ValueOf(&runtime.With).Elem(),

		// type definitions
		"AddInManager":                                   reflect.ValueOf((*runtime.AddInManager)(nil)),
		"AddInStatus":                                    reflect.ValueOf((*runtime.AddInStatus)(nil)),
		"Caller":                                         reflect.ValueOf((*runtime.Caller)(nil)),
		"ConcurrentContext":                              reflect.ValueOf((*runtime.ConcurrentContext)(nil)),
		"ConcurrentContextProvider":                      reflect.ValueOf((*runtime.ConcurrentContextProvider)(nil)),
		"Context":                                        reflect.ValueOf((*runtime.Context)(nil)),
		"ContextBehavior":                                reflect.ValueOf((*runtime.ContextBehavior)(nil)),
		"ContextOptions":                                 reflect.ValueOf((*runtime.ContextOptions)(nil)),
		"CurrentContextProvider":                         reflect.ValueOf((*runtime.CurrentContextProvider)(nil)),
		"EntityManager":                                  reflect.ValueOf((*runtime.EntityManager)(nil)),
		"EntityTree":                                     reflect.ValueOf((*runtime.EntityTree)(nil)),
		"EventAddInStateChanged":                         reflect.ValueOf((*runtime.EventAddInStateChanged)(nil)),
		"EventAddInStateChangedHandler":                  reflect.ValueOf((*runtime.EventAddInStateChangedHandler)(nil)),
		"EventContextRunningEvent":                       reflect.ValueOf((*runtime.EventContextRunningEvent)(nil)),
		"EventContextRunningEventHandler":                reflect.ValueOf((*runtime.EventContextRunningEventHandler)(nil)),
		"EventEntityManagerAddEntity":                    reflect.ValueOf((*runtime.EventEntityManagerAddEntity)(nil)),
		"EventEntityManagerAddEntityHandler":             reflect.ValueOf((*runtime.EventEntityManagerAddEntityHandler)(nil)),
		"EventEntityManagerEntityAddComponents":          reflect.ValueOf((*runtime.EventEntityManagerEntityAddComponents)(nil)),
		"EventEntityManagerEntityAddComponentsHandler":   reflect.ValueOf((*runtime.EventEntityManagerEntityAddComponentsHandler)(nil)),
		"EventEntityManagerEntityComponentEnableChanged": reflect.ValueOf((*runtime.EventEntityManagerEntityComponentEnableChanged)(nil)),
		"EventEntityManagerEntityComponentEnableChangedHandler": reflect.ValueOf((*runtime.EventEntityManagerEntityComponentEnableChangedHandler)(nil)),
		"EventEntityManagerEntityFirstTouchComponent":           reflect.ValueOf((*runtime.EventEntityManagerEntityFirstTouchComponent)(nil)),
		"EventEntityManagerEntityFirstTouchComponentHandler":    reflect.ValueOf((*runtime.EventEntityManagerEntityFirstTouchComponentHandler)(nil)),
		"EventEntityManagerEntityRemoveComponent":               reflect.ValueOf((*runtime.EventEntityManagerEntityRemoveComponent)(nil)),
		"EventEntityManagerEntityRemoveComponentHandler":        reflect.ValueOf((*runtime.EventEntityManagerEntityRemoveComponentHandler)(nil)),
		"EventEntityManagerRemoveEntity":                        reflect.ValueOf((*runtime.EventEntityManagerRemoveEntity)(nil)),
		"EventEntityManagerRemoveEntityHandler":                 reflect.ValueOf((*runtime.EventEntityManagerRemoveEntityHandler)(nil)),
		"EventEntityTreeAddNode":                                reflect.ValueOf((*runtime.EventEntityTreeAddNode)(nil)),
		"EventEntityTreeAddNodeHandler":                         reflect.ValueOf((*runtime.EventEntityTreeAddNodeHandler)(nil)),
		"EventEntityTreeMoveNode":                               reflect.ValueOf((*runtime.EventEntityTreeMoveNode)(nil)),
		"EventEntityTreeMoveNodeHandler":                        reflect.ValueOf((*runtime.EventEntityTreeMoveNodeHandler)(nil)),
		"EventEntityTreeRemoveNode":                             reflect.ValueOf((*runtime.EventEntityTreeRemoveNode)(nil)),
		"EventEntityTreeRemoveNodeHandler":                      reflect.ValueOf((*runtime.EventEntityTreeRemoveNodeHandler)(nil)),
		"EventInstallAddIn":                                     reflect.ValueOf((*runtime.EventInstallAddIn)(nil)),
		"EventInstallAddInHandler":                              reflect.ValueOf((*runtime.EventInstallAddInHandler)(nil)),
		"EventUninstallAddIn":                                   reflect.ValueOf((*runtime.EventUninstallAddIn)(nil)),
		"EventUninstallAddInHandler":                            reflect.ValueOf((*runtime.EventUninstallAddInHandler)(nil)),
		"Frame":                                                 reflect.ValueOf((*runtime.Frame)(nil)),
		"GC":                                                    reflect.ValueOf((*runtime.GC)(nil)),
		"GCCollector":                                           reflect.ValueOf((*runtime.GCCollector)(nil)),
		"IAddInManagerEventTab":                                 reflect.ValueOf((*runtime.IAddInManagerEventTab)(nil)),
		"IContextRunningEventTab":                               reflect.ValueOf((*runtime.IContextRunningEventTab)(nil)),
		"IEntityManagerEventTab":                                reflect.ValueOf((*runtime.IEntityManagerEventTab)(nil)),
		"IEntityTreeEventTab":                                   reflect.ValueOf((*runtime.IEntityTreeEventTab)(nil)),
		"RunningEvent":                                          reflect.ValueOf((*runtime.RunningEvent)(nil)),
		"RunningEventCB":                                        reflect.ValueOf((*runtime.RunningEventCB)(nil)),

		// interface wrapper definitions
		"_AddInManager":                          reflect.ValueOf((*_git_golaxy_org_core_runtime_AddInManager)(nil)),
		"_AddInStatus":                           reflect.ValueOf((*_git_golaxy_org_core_runtime_AddInStatus)(nil)),
		"_Caller":                                reflect.ValueOf((*_git_golaxy_org_core_runtime_Caller)(nil)),
		"_ConcurrentContext":                     reflect.ValueOf((*_git_golaxy_org_core_runtime_ConcurrentContext)(nil)),
		"_ConcurrentContextProvider":             reflect.ValueOf((*_git_golaxy_org_core_runtime_ConcurrentContextProvider)(nil)),
		"_Context":                               reflect.ValueOf((*_git_golaxy_org_core_runtime_Context)(nil)),
		"_CurrentContextProvider":                reflect.ValueOf((*_git_golaxy_org_core_runtime_CurrentContextProvider)(nil)),
		"_EntityManager":                         reflect.ValueOf((*_git_golaxy_org_core_runtime_EntityManager)(nil)),
		"_EntityTree":                            reflect.ValueOf((*_git_golaxy_org_core_runtime_EntityTree)(nil)),
		"_EventAddInStateChanged":                reflect.ValueOf((*_git_golaxy_org_core_runtime_EventAddInStateChanged)(nil)),
		"_EventContextRunningEvent":              reflect.ValueOf((*_git_golaxy_org_core_runtime_EventContextRunningEvent)(nil)),
		"_EventEntityManagerAddEntity":           reflect.ValueOf((*_git_golaxy_org_core_runtime_EventEntityManagerAddEntity)(nil)),
		"_EventEntityManagerEntityAddComponents": reflect.ValueOf((*_git_golaxy_org_core_runtime_EventEntityManagerEntityAddComponents)(nil)),
		"_EventEntityManagerEntityComponentEnableChanged": reflect.ValueOf((*_git_golaxy_org_core_runtime_EventEntityManagerEntityComponentEnableChanged)(nil)),
		"_EventEntityManagerEntityFirstTouchComponent":    reflect.ValueOf((*_git_golaxy_org_core_runtime_EventEntityManagerEntityFirstTouchComponent)(nil)),
		"_EventEntityManagerEntityRemoveComponent":        reflect.ValueOf((*_git_golaxy_org_core_runtime_EventEntityManagerEntityRemoveComponent)(nil)),
		"_EventEntityManagerRemoveEntity":                 reflect.ValueOf((*_git_golaxy_org_core_runtime_EventEntityManagerRemoveEntity)(nil)),
		"_EventEntityTreeAddNode":                         reflect.ValueOf((*_git_golaxy_org_core_runtime_EventEntityTreeAddNode)(nil)),
		"_EventEntityTreeMoveNode":                        reflect.ValueOf((*_git_golaxy_org_core_runtime_EventEntityTreeMoveNode)(nil)),
		"_EventEntityTreeRemoveNode":                      reflect.ValueOf((*_git_golaxy_org_core_runtime_EventEntityTreeRemoveNode)(nil)),
		"_EventInstallAddIn":                              reflect.ValueOf((*_git_golaxy_org_core_runtime_EventInstallAddIn)(nil)),
		"_EventUninstallAddIn":                            reflect.ValueOf((*_git_golaxy_org_core_runtime_EventUninstallAddIn)(nil)),
		"_Frame":                                          reflect.ValueOf((*_git_golaxy_org_core_runtime_Frame)(nil)),
		"_GC":                                             reflect.ValueOf((*_git_golaxy_org_core_runtime_GC)(nil)),
		"_GCCollector":                                    reflect.ValueOf((*_git_golaxy_org_core_runtime_GCCollector)(nil)),
		"_IAddInManagerEventTab":                          reflect.ValueOf((*_git_golaxy_org_core_runtime_IAddInManagerEventTab)(nil)),
		"_IContextRunningEventTab":                        reflect.ValueOf((*_git_golaxy_org_core_runtime_IContextRunningEventTab)(nil)),
		"_IEntityManagerEventTab":                         reflect.ValueOf((*_git_golaxy_org_core_runtime_IEntityManagerEventTab)(nil)),
		"_IEntityTreeEventTab":                            reflect.ValueOf((*_git_golaxy_org_core_runtime_IEntityTreeEventTab)(nil)),
	}
}

// _git_golaxy_org_core_runtime_AddInManager is an interface wrapper for AddInManager type
type _git_golaxy_org_core_runtime_AddInManager struct {
	IValue                  interface{}
	WAddInManager           func() extension.AddInManager
	WEventAddInStateChanged func() event.IEvent
	WEventInstallAddIn      func() event.IEvent
	WEventUninstallAddIn    func() event.IEvent
	WGetStatusByID          func(id uint64) (extension.AddInStatus, bool)
	WGetStatusByName        func(name string) (extension.AddInStatus, bool)
	WInstall                func(addInFace iface.FaceAny, name ...string) extension.AddInStatus
	WListStatuses           func() []extension.AddInStatus
	WUninstall              func(name string)
}

func (W _git_golaxy_org_core_runtime_AddInManager) AddInManager() extension.AddInManager {
	return W.WAddInManager()
}
func (W _git_golaxy_org_core_runtime_AddInManager) EventAddInStateChanged() event.IEvent {
	return W.WEventAddInStateChanged()
}
func (W _git_golaxy_org_core_runtime_AddInManager) EventInstallAddIn() event.IEvent {
	return W.WEventInstallAddIn()
}
func (W _git_golaxy_org_core_runtime_AddInManager) EventUninstallAddIn() event.IEvent {
	return W.WEventUninstallAddIn()
}
func (W _git_golaxy_org_core_runtime_AddInManager) GetStatusByID(id uint64) (extension.AddInStatus, bool) {
	return W.WGetStatusByID(id)
}
func (W _git_golaxy_org_core_runtime_AddInManager) GetStatusByName(name string) (extension.AddInStatus, bool) {
	return W.WGetStatusByName(name)
}
func (W _git_golaxy_org_core_runtime_AddInManager) Install(addInFace iface.FaceAny, name ...string) extension.AddInStatus {
	return W.WInstall(addInFace, name...)
}
func (W _git_golaxy_org_core_runtime_AddInManager) ListStatuses() []extension.AddInStatus {
	return W.WListStatuses()
}
func (W _git_golaxy_org_core_runtime_AddInManager) Uninstall(name string) { W.WUninstall(name) }

// _git_golaxy_org_core_runtime_AddInStatus is an interface wrapper for AddInStatus type
type _git_golaxy_org_core_runtime_AddInStatus struct {
	IValue        interface{}
	WID           func() uint64
	WInstanceFace func() iface.FaceAny
	WName         func() string
	WReflected    func() reflect.Value
	WState        func() extension.AddInState
	WString       func() string
}

func (W _git_golaxy_org_core_runtime_AddInStatus) ID() uint64 { return W.WID() }
func (W _git_golaxy_org_core_runtime_AddInStatus) InstanceFace() iface.FaceAny {
	return W.WInstanceFace()
}
func (W _git_golaxy_org_core_runtime_AddInStatus) Name() string                { return W.WName() }
func (W _git_golaxy_org_core_runtime_AddInStatus) Reflected() reflect.Value    { return W.WReflected() }
func (W _git_golaxy_org_core_runtime_AddInStatus) State() extension.AddInState { return W.WState() }
func (W _git_golaxy_org_core_runtime_AddInStatus) String() string {
	if W.WString == nil {
		return ""
	}
	return W.WString()
}

// _git_golaxy_org_core_runtime_Caller is an interface wrapper for Caller type
type _git_golaxy_org_core_runtime_Caller struct {
	IValue              interface{}
	WPost               func(fun generic.ActionVar1[runtime.Context, any], args ...any) error
	WPostDelegate       func(fun generic.DelegateVoidVar1[runtime.Context, any], args ...any) error
	WSubmit             func(fun generic.FuncVar1[runtime.Context, any, async.Result], args ...any) async.Future
	WSubmitDelegate     func(fun generic.DelegateVar1[runtime.Context, any, async.Result], args ...any) async.Future
	WSubmitDelegateVoid func(fun generic.DelegateVoidVar1[runtime.Context, any], args ...any) async.Future
	WSubmitVoid         func(fun generic.ActionVar1[runtime.Context, any], args ...any) async.Future
}

func (W _git_golaxy_org_core_runtime_Caller) Post(fun generic.ActionVar1[runtime.Context, any], args ...any) error {
	return W.WPost(fun, args...)
}
func (W _git_golaxy_org_core_runtime_Caller) PostDelegate(fun generic.DelegateVoidVar1[runtime.Context, any], args ...any) error {
	return W.WPostDelegate(fun, args...)
}
func (W _git_golaxy_org_core_runtime_Caller) Submit(fun generic.FuncVar1[runtime.Context, any, async.Result], args ...any) async.Future {
	return W.WSubmit(fun, args...)
}
func (W _git_golaxy_org_core_runtime_Caller) SubmitDelegate(fun generic.DelegateVar1[runtime.Context, any, async.Result], args ...any) async.Future {
	return W.WSubmitDelegate(fun, args...)
}
func (W _git_golaxy_org_core_runtime_Caller) SubmitDelegateVoid(fun generic.DelegateVoidVar1[runtime.Context, any], args ...any) async.Future {
	return W.WSubmitDelegateVoid(fun, args...)
}
func (W _git_golaxy_org_core_runtime_Caller) SubmitVoid(fun generic.ActionVar1[runtime.Context, any], args ...any) async.Future {
	return W.WSubmitVoid(fun, args...)
}

// _git_golaxy_org_core_runtime_ConcurrentContext is an interface wrapper for ConcurrentContext type
type _git_golaxy_org_core_runtime_ConcurrentContext struct {
	IValue                  interface{}
	WAsyncScope             func() *async.Scope
	WAutoRecover            func() bool
	WBlockedFutureID        func() async.FutureID
	WConcurrentContextCache func() iface.Cache
	WDeadline               func() (deadline time.Time, ok bool)
	WDone                   func() <-chan struct{}
	WErr                    func() error
	WExecutorID             func() async.ExecutorID
	WID                     func() uid.ID
	WLastWaitRejectID       func() async.FutureID
	WName                   func() string
	WParentContext          func() context.Context
	WPost                   func(fun generic.ActionVar1[runtime.Context, any], args ...any) error
	WPostDelegate           func(fun generic.DelegateVoidVar1[runtime.Context, any], args ...any) error
	WReportError            func() chan error
	WString                 func() string
	WSubmit                 func(fun generic.FuncVar1[runtime.Context, any, async.Result], args ...any) async.Future
	WSubmitDelegate         func(fun generic.DelegateVar1[runtime.Context, any, async.Result], args ...any) async.Future
	WSubmitDelegateVoid     func(fun generic.DelegateVoidVar1[runtime.Context, any], args ...any) async.Future
	WSubmitVoid             func(fun generic.ActionVar1[runtime.Context, any], args ...any) async.Future
	WTerminate              func() async.Signal
	WTerminated             func() async.Signal
	WValue                  func(key any) any
	WWaitGroup              func() corectx.WaitGroup
}

func (W _git_golaxy_org_core_runtime_ConcurrentContext) AsyncScope() *async.Scope {
	return W.WAsyncScope()
}
func (W _git_golaxy_org_core_runtime_ConcurrentContext) AutoRecover() bool { return W.WAutoRecover() }
func (W _git_golaxy_org_core_runtime_ConcurrentContext) BlockedFutureID() async.FutureID {
	return W.WBlockedFutureID()
}
func (W _git_golaxy_org_core_runtime_ConcurrentContext) ConcurrentContextCache() iface.Cache {
	return W.WConcurrentContextCache()
}
func (W _git_golaxy_org_core_runtime_ConcurrentContext) Deadline() (deadline time.Time, ok bool) {
	return W.WDeadline()
}
func (W _git_golaxy_org_core_runtime_ConcurrentContext) Done() <-chan struct{} { return W.WDone() }
func (W _git_golaxy_org_core_runtime_ConcurrentContext) Err() error            { return W.WErr() }
func (W _git_golaxy_org_core_runtime_ConcurrentContext) ExecutorID() async.ExecutorID {
	return W.WExecutorID()
}
func (W _git_golaxy_org_core_runtime_ConcurrentContext) ID() uid.ID { return W.WID() }
func (W _git_golaxy_org_core_runtime_ConcurrentContext) LastWaitRejectID() async.FutureID {
	return W.WLastWaitRejectID()
}
func (W _git_golaxy_org_core_runtime_ConcurrentContext) Name() string { return W.WName() }
func (W _git_golaxy_org_core_runtime_ConcurrentContext) ParentContext() context.Context {
	return W.WParentContext()
}
func (W _git_golaxy_org_core_runtime_ConcurrentContext) Post(fun generic.ActionVar1[runtime.Context, any], args ...any) error {
	return W.WPost(fun, args...)
}
func (W _git_golaxy_org_core_runtime_ConcurrentContext) PostDelegate(fun generic.DelegateVoidVar1[runtime.Context, any], args ...any) error {
	return W.WPostDelegate(fun, args...)
}
func (W _git_golaxy_org_core_runtime_ConcurrentContext) ReportError() chan error {
	return W.WReportError()
}
func (W _git_golaxy_org_core_runtime_ConcurrentContext) String() string {
	if W.WString == nil {
		return ""
	}
	return W.WString()
}
func (W _git_golaxy_org_core_runtime_ConcurrentContext) Submit(fun generic.FuncVar1[runtime.Context, any, async.Result], args ...any) async.Future {
	return W.WSubmit(fun, args...)
}
func (W _git_golaxy_org_core_runtime_ConcurrentContext) SubmitDelegate(fun generic.DelegateVar1[runtime.Context, any, async.Result], args ...any) async.Future {
	return W.WSubmitDelegate(fun, args...)
}
func (W _git_golaxy_org_core_runtime_ConcurrentContext) SubmitDelegateVoid(fun generic.DelegateVoidVar1[runtime.Context, any], args ...any) async.Future {
	return W.WSubmitDelegateVoid(fun, args...)
}
func (W _git_golaxy_org_core_runtime_ConcurrentContext) SubmitVoid(fun generic.ActionVar1[runtime.Context, any], args ...any) async.Future {
	return W.WSubmitVoid(fun, args...)
}
func (W _git_golaxy_org_core_runtime_ConcurrentContext) Terminate() async.Signal {
	return W.WTerminate()
}
func (W _git_golaxy_org_core_runtime_ConcurrentContext) Terminated() async.Signal {
	return W.WTerminated()
}
func (W _git_golaxy_org_core_runtime_ConcurrentContext) Value(key any) any { return W.WValue(key) }
func (W _git_golaxy_org_core_runtime_ConcurrentContext) WaitGroup() corectx.WaitGroup {
	return W.WWaitGroup()
}

// _git_golaxy_org_core_runtime_ConcurrentContextProvider is an interface wrapper for ConcurrentContextProvider type
type _git_golaxy_org_core_runtime_ConcurrentContextProvider struct {
	IValue                  interface{}
	WConcurrentContextCache func() iface.Cache
}

func (W _git_golaxy_org_core_runtime_ConcurrentContextProvider) ConcurrentContextCache() iface.Cache {
	return W.WConcurrentContextCache()
}

// _git_golaxy_org_core_runtime_Context is an interface wrapper for Context type
type _git_golaxy_org_core_runtime_Context struct {
	IValue                    interface{}
	WAddInManager             func() extension.AddInManager
	WAfterFutureWait          func(futureID async.FutureID)
	WAsyncScope               func() *async.Scope
	WAutoRecover              func() bool
	WBeforeFutureWait         func(futureID async.FutureID, completionExecutorID async.ExecutorID) error
	WBlockedFutureID          func() async.FutureID
	WCollectGC                func(gc runtime.GC)
	WConcurrentContextCache   func() iface.Cache
	WCurrentContextCache      func() iface.Cache
	WDeadline                 func() (deadline time.Time, ok bool)
	WDone                     func() <-chan struct{}
	WEntityManager            func() runtime.EntityManager
	WEntityTree               func() runtime.EntityTree
	WErr                      func() error
	WEventContextRunningEvent func() event.IEvent
	WExecutorID               func() async.ExecutorID
	WFrame                    func() runtime.Frame
	WID                       func() uid.ID
	WInstanceFaceCache        func() iface.Cache
	WLastWaitRejectID         func() async.FutureID
	WManaged                  func() *event.ManagedHandles
	WName                     func() string
	WParentContext            func() context.Context
	WPost                     func(fun generic.ActionVar1[runtime.Context, any], args ...any) error
	WPostDelegate             func(fun generic.DelegateVoidVar1[runtime.Context, any], args ...any) error
	WReflected                func() reflect.Value
	WReportError              func() chan error
	WString                   func() string
	WSubmit                   func(fun generic.FuncVar1[runtime.Context, any, async.Result], args ...any) async.Future
	WSubmitDelegate           func(fun generic.DelegateVar1[runtime.Context, any, async.Result], args ...any) async.Future
	WSubmitDelegateVoid       func(fun generic.DelegateVoidVar1[runtime.Context, any], args ...any) async.Future
	WSubmitVoid               func(fun generic.ActionVar1[runtime.Context, any], args ...any) async.Future
	WTerminate                func() async.Signal
	WTerminated               func() async.Signal
	WValue                    func(key any) any
	WWaitGroup                func() corectx.WaitGroup
}

func (W _git_golaxy_org_core_runtime_Context) AddInManager() extension.AddInManager {
	return W.WAddInManager()
}
func (W _git_golaxy_org_core_runtime_Context) AfterFutureWait(futureID async.FutureID) {
	W.WAfterFutureWait(futureID)
}
func (W _git_golaxy_org_core_runtime_Context) AsyncScope() *async.Scope { return W.WAsyncScope() }
func (W _git_golaxy_org_core_runtime_Context) AutoRecover() bool        { return W.WAutoRecover() }
func (W _git_golaxy_org_core_runtime_Context) BeforeFutureWait(futureID async.FutureID, completionExecutorID async.ExecutorID) error {
	return W.WBeforeFutureWait(futureID, completionExecutorID)
}
func (W _git_golaxy_org_core_runtime_Context) BlockedFutureID() async.FutureID {
	return W.WBlockedFutureID()
}
func (W _git_golaxy_org_core_runtime_Context) CollectGC(gc runtime.GC) { W.WCollectGC(gc) }
func (W _git_golaxy_org_core_runtime_Context) ConcurrentContextCache() iface.Cache {
	return W.WConcurrentContextCache()
}
func (W _git_golaxy_org_core_runtime_Context) CurrentContextCache() iface.Cache {
	return W.WCurrentContextCache()
}
func (W _git_golaxy_org_core_runtime_Context) Deadline() (deadline time.Time, ok bool) {
	return W.WDeadline()
}
func (W _git_golaxy_org_core_runtime_Context) Done() <-chan struct{} { return W.WDone() }
func (W _git_golaxy_org_core_runtime_Context) EntityManager() runtime.EntityManager {
	return W.WEntityManager()
}
func (W _git_golaxy_org_core_runtime_Context) EntityTree() runtime.EntityTree { return W.WEntityTree() }
func (W _git_golaxy_org_core_runtime_Context) Err() error                     { return W.WErr() }
func (W _git_golaxy_org_core_runtime_Context) EventContextRunningEvent() event.IEvent {
	return W.WEventContextRunningEvent()
}
func (W _git_golaxy_org_core_runtime_Context) ExecutorID() async.ExecutorID { return W.WExecutorID() }
func (W _git_golaxy_org_core_runtime_Context) Frame() runtime.Frame         { return W.WFrame() }
func (W _git_golaxy_org_core_runtime_Context) ID() uid.ID                   { return W.WID() }
func (W _git_golaxy_org_core_runtime_Context) InstanceFaceCache() iface.Cache {
	return W.WInstanceFaceCache()
}
func (W _git_golaxy_org_core_runtime_Context) LastWaitRejectID() async.FutureID {
	return W.WLastWaitRejectID()
}
func (W _git_golaxy_org_core_runtime_Context) Managed() *event.ManagedHandles { return W.WManaged() }
func (W _git_golaxy_org_core_runtime_Context) Name() string                   { return W.WName() }
func (W _git_golaxy_org_core_runtime_Context) ParentContext() context.Context {
	return W.WParentContext()
}
func (W _git_golaxy_org_core_runtime_Context) Post(fun generic.ActionVar1[runtime.Context, any], args ...any) error {
	return W.WPost(fun, args...)
}
func (W _git_golaxy_org_core_runtime_Context) PostDelegate(fun generic.DelegateVoidVar1[runtime.Context, any], args ...any) error {
	return W.WPostDelegate(fun, args...)
}
func (W _git_golaxy_org_core_runtime_Context) Reflected() reflect.Value { return W.WReflected() }
func (W _git_golaxy_org_core_runtime_Context) ReportError() chan error  { return W.WReportError() }
func (W _git_golaxy_org_core_runtime_Context) String() string {
	if W.WString == nil {
		return ""
	}
	return W.WString()
}
func (W _git_golaxy_org_core_runtime_Context) Submit(fun generic.FuncVar1[runtime.Context, any, async.Result], args ...any) async.Future {
	return W.WSubmit(fun, args...)
}
func (W _git_golaxy_org_core_runtime_Context) SubmitDelegate(fun generic.DelegateVar1[runtime.Context, any, async.Result], args ...any) async.Future {
	return W.WSubmitDelegate(fun, args...)
}
func (W _git_golaxy_org_core_runtime_Context) SubmitDelegateVoid(fun generic.DelegateVoidVar1[runtime.Context, any], args ...any) async.Future {
	return W.WSubmitDelegateVoid(fun, args...)
}
func (W _git_golaxy_org_core_runtime_Context) SubmitVoid(fun generic.ActionVar1[runtime.Context, any], args ...any) async.Future {
	return W.WSubmitVoid(fun, args...)
}
func (W _git_golaxy_org_core_runtime_Context) Terminate() async.Signal      { return W.WTerminate() }
func (W _git_golaxy_org_core_runtime_Context) Terminated() async.Signal     { return W.WTerminated() }
func (W _git_golaxy_org_core_runtime_Context) Value(key any) any            { return W.WValue(key) }
func (W _git_golaxy_org_core_runtime_Context) WaitGroup() corectx.WaitGroup { return W.WWaitGroup() }

// _git_golaxy_org_core_runtime_CurrentContextProvider is an interface wrapper for CurrentContextProvider type
type _git_golaxy_org_core_runtime_CurrentContextProvider struct {
	IValue                  interface{}
	WConcurrentContextCache func() iface.Cache
	WCurrentContextCache    func() iface.Cache
}

func (W _git_golaxy_org_core_runtime_CurrentContextProvider) ConcurrentContextCache() iface.Cache {
	return W.WConcurrentContextCache()
}
func (W _git_golaxy_org_core_runtime_CurrentContextProvider) CurrentContextCache() iface.Cache {
	return W.WCurrentContextCache()
}

// _git_golaxy_org_core_runtime_EntityManager is an interface wrapper for EntityManager type
type _git_golaxy_org_core_runtime_EntityManager struct {
	IValue                                          interface{}
	WAddEntity                                      func(entity ec.Entity) error
	WConcurrentContextCache                         func() iface.Cache
	WCountEntities                                  func() int
	WCurrentContextCache                            func() iface.Cache
	WEachEntities                                   func(fun generic.Action1[ec.Entity])
	WEventEntityManagerAddEntity                    func() event.IEvent
	WEventEntityManagerEntityAddComponents          func() event.IEvent
	WEventEntityManagerEntityComponentEnableChanged func() event.IEvent
	WEventEntityManagerEntityFirstTouchComponent    func() event.IEvent
	WEventEntityManagerEntityRemoveComponent        func() event.IEvent
	WEventEntityManagerRemoveEntity                 func() event.IEvent
	WFilterEntities                                 func(fun generic.Func1[ec.Entity, bool]) []ec.Entity
	WGetEntity                                      func(id uid.ID) (ec.Entity, bool)
	WListEntities                                   func() []ec.Entity
	WRangeEntities                                  func(fun generic.Func1[ec.Entity, bool])
	WRemoveEntity                                   func(id uid.ID)
	WReversedEachEntities                           func(fun generic.Action1[ec.Entity])
	WReversedRangeEntities                          func(fun generic.Func1[ec.Entity, bool])
}

func (W _git_golaxy_org_core_runtime_EntityManager) AddEntity(entity ec.Entity) error {
	return W.WAddEntity(entity)
}
func (W _git_golaxy_org_core_runtime_EntityManager) ConcurrentContextCache() iface.Cache {
	return W.WConcurrentContextCache()
}
func (W _git_golaxy_org_core_runtime_EntityManager) CountEntities() int { return W.WCountEntities() }
func (W _git_golaxy_org_core_runtime_EntityManager) CurrentContextCache() iface.Cache {
	return W.WCurrentContextCache()
}
func (W _git_golaxy_org_core_runtime_EntityManager) EachEntities(fun generic.Action1[ec.Entity]) {
	W.WEachEntities(fun)
}
func (W _git_golaxy_org_core_runtime_EntityManager) EventEntityManagerAddEntity() event.IEvent {
	return W.WEventEntityManagerAddEntity()
}
func (W _git_golaxy_org_core_runtime_EntityManager) EventEntityManagerEntityAddComponents() event.IEvent {
	return W.WEventEntityManagerEntityAddComponents()
}
func (W _git_golaxy_org_core_runtime_EntityManager) EventEntityManagerEntityComponentEnableChanged() event.IEvent {
	return W.WEventEntityManagerEntityComponentEnableChanged()
}
func (W _git_golaxy_org_core_runtime_EntityManager) EventEntityManagerEntityFirstTouchComponent() event.IEvent {
	return W.WEventEntityManagerEntityFirstTouchComponent()
}
func (W _git_golaxy_org_core_runtime_EntityManager) EventEntityManagerEntityRemoveComponent() event.IEvent {
	return W.WEventEntityManagerEntityRemoveComponent()
}
func (W _git_golaxy_org_core_runtime_EntityManager) EventEntityManagerRemoveEntity() event.IEvent {
	return W.WEventEntityManagerRemoveEntity()
}
func (W _git_golaxy_org_core_runtime_EntityManager) FilterEntities(fun generic.Func1[ec.Entity, bool]) []ec.Entity {
	return W.WFilterEntities(fun)
}
func (W _git_golaxy_org_core_runtime_EntityManager) GetEntity(id uid.ID) (ec.Entity, bool) {
	return W.WGetEntity(id)
}
func (W _git_golaxy_org_core_runtime_EntityManager) ListEntities() []ec.Entity {
	return W.WListEntities()
}
func (W _git_golaxy_org_core_runtime_EntityManager) RangeEntities(fun generic.Func1[ec.Entity, bool]) {
	W.WRangeEntities(fun)
}
func (W _git_golaxy_org_core_runtime_EntityManager) RemoveEntity(id uid.ID) { W.WRemoveEntity(id) }
func (W _git_golaxy_org_core_runtime_EntityManager) ReversedEachEntities(fun generic.Action1[ec.Entity]) {
	W.WReversedEachEntities(fun)
}
func (W _git_golaxy_org_core_runtime_EntityManager) ReversedRangeEntities(fun generic.Func1[ec.Entity, bool]) {
	W.WReversedRangeEntities(fun)
}

// _git_golaxy_org_core_runtime_EntityTree is an interface wrapper for EntityTree type
type _git_golaxy_org_core_runtime_EntityTree struct {
	IValue                     interface{}
	WAddChild                  func(parentID uid.ID, childID uid.ID) error
	WConcurrentContextCache    func() iface.Cache
	WCountChildren             func(parentID uid.ID) (int, error)
	WCurrentContextCache       func() iface.Cache
	WDetachNode                func(childID uid.ID) error
	WEachChildren              func(parentID uid.ID, fun generic.Action1[ec.Entity]) error
	WEventEntityTreeAddNode    func() event.IEvent
	WEventEntityTreeMoveNode   func() event.IEvent
	WEventEntityTreeRemoveNode func() event.IEvent
	WFilterChildren            func(parentID uid.ID, fun generic.Func1[ec.Entity, bool]) ([]ec.Entity, error)
	WGetParent                 func(childID uid.ID) (ec.Entity, error)
	WIsFree                    func(entityID uid.ID) (bool, error)
	WIsLeaf                    func(entityID uid.ID) (bool, error)
	WIsRoot                    func(entityID uid.ID) (bool, error)
	WListChildren              func(parentID uid.ID) ([]ec.Entity, error)
	WMakeRoot                  func(entityID uid.ID) error
	WMoveNode                  func(childID uid.ID, parentID uid.ID) error
	WRangeChildren             func(parentID uid.ID, fun generic.Func1[ec.Entity, bool]) error
	WRemoveNode                func(childID uid.ID) error
	WReversedEachChildren      func(parentID uid.ID, fun generic.Action1[ec.Entity]) error
	WReversedRangeChildren     func(parentID uid.ID, fun generic.Func1[ec.Entity, bool]) error
}

func (W _git_golaxy_org_core_runtime_EntityTree) AddChild(parentID uid.ID, childID uid.ID) error {
	return W.WAddChild(parentID, childID)
}
func (W _git_golaxy_org_core_runtime_EntityTree) ConcurrentContextCache() iface.Cache {
	return W.WConcurrentContextCache()
}
func (W _git_golaxy_org_core_runtime_EntityTree) CountChildren(parentID uid.ID) (int, error) {
	return W.WCountChildren(parentID)
}
func (W _git_golaxy_org_core_runtime_EntityTree) CurrentContextCache() iface.Cache {
	return W.WCurrentContextCache()
}
func (W _git_golaxy_org_core_runtime_EntityTree) DetachNode(childID uid.ID) error {
	return W.WDetachNode(childID)
}
func (W _git_golaxy_org_core_runtime_EntityTree) EachChildren(parentID uid.ID, fun generic.Action1[ec.Entity]) error {
	return W.WEachChildren(parentID, fun)
}
func (W _git_golaxy_org_core_runtime_EntityTree) EventEntityTreeAddNode() event.IEvent {
	return W.WEventEntityTreeAddNode()
}
func (W _git_golaxy_org_core_runtime_EntityTree) EventEntityTreeMoveNode() event.IEvent {
	return W.WEventEntityTreeMoveNode()
}
func (W _git_golaxy_org_core_runtime_EntityTree) EventEntityTreeRemoveNode() event.IEvent {
	return W.WEventEntityTreeRemoveNode()
}
func (W _git_golaxy_org_core_runtime_EntityTree) FilterChildren(parentID uid.ID, fun generic.Func1[ec.Entity, bool]) ([]ec.Entity, error) {
	return W.WFilterChildren(parentID, fun)
}
func (W _git_golaxy_org_core_runtime_EntityTree) GetParent(childID uid.ID) (ec.Entity, error) {
	return W.WGetParent(childID)
}
func (W _git_golaxy_org_core_runtime_EntityTree) IsFree(entityID uid.ID) (bool, error) {
	return W.WIsFree(entityID)
}
func (W _git_golaxy_org_core_runtime_EntityTree) IsLeaf(entityID uid.ID) (bool, error) {
	return W.WIsLeaf(entityID)
}
func (W _git_golaxy_org_core_runtime_EntityTree) IsRoot(entityID uid.ID) (bool, error) {
	return W.WIsRoot(entityID)
}
func (W _git_golaxy_org_core_runtime_EntityTree) ListChildren(parentID uid.ID) ([]ec.Entity, error) {
	return W.WListChildren(parentID)
}
func (W _git_golaxy_org_core_runtime_EntityTree) MakeRoot(entityID uid.ID) error {
	return W.WMakeRoot(entityID)
}
func (W _git_golaxy_org_core_runtime_EntityTree) MoveNode(childID uid.ID, parentID uid.ID) error {
	return W.WMoveNode(childID, parentID)
}
func (W _git_golaxy_org_core_runtime_EntityTree) RangeChildren(parentID uid.ID, fun generic.Func1[ec.Entity, bool]) error {
	return W.WRangeChildren(parentID, fun)
}
func (W _git_golaxy_org_core_runtime_EntityTree) RemoveNode(childID uid.ID) error {
	return W.WRemoveNode(childID)
}
func (W _git_golaxy_org_core_runtime_EntityTree) ReversedEachChildren(parentID uid.ID, fun generic.Action1[ec.Entity]) error {
	return W.WReversedEachChildren(parentID, fun)
}
func (W _git_golaxy_org_core_runtime_EntityTree) ReversedRangeChildren(parentID uid.ID, fun generic.Func1[ec.Entity, bool]) error {
	return W.WReversedRangeChildren(parentID, fun)
}

// _git_golaxy_org_core_runtime_EventAddInStateChanged is an interface wrapper for EventAddInStateChanged type
type _git_golaxy_org_core_runtime_EventAddInStateChanged struct {
	IValue               interface{}
	WOnAddInStateChanged func(status runtime.AddInStatus, state extension.AddInState)
}

func (W _git_golaxy_org_core_runtime_EventAddInStateChanged) OnAddInStateChanged(status runtime.AddInStatus, state extension.AddInState) {
	W.WOnAddInStateChanged(status, state)
}

// _git_golaxy_org_core_runtime_EventContextRunningEvent is an interface wrapper for EventContextRunningEvent type
type _git_golaxy_org_core_runtime_EventContextRunningEvent struct {
	IValue                 interface{}
	WOnContextRunningEvent func(ctx runtime.Context, runningEvent runtime.RunningEvent, args ...any)
}

func (W _git_golaxy_org_core_runtime_EventContextRunningEvent) OnContextRunningEvent(ctx runtime.Context, runningEvent runtime.RunningEvent, args ...any) {
	W.WOnContextRunningEvent(ctx, runningEvent, args...)
}

// _git_golaxy_org_core_runtime_EventEntityManagerAddEntity is an interface wrapper for EventEntityManagerAddEntity type
type _git_golaxy_org_core_runtime_EventEntityManagerAddEntity struct {
	IValue                    interface{}
	WOnEntityManagerAddEntity func(entityManager runtime.EntityManager, entity ec.Entity)
}

func (W _git_golaxy_org_core_runtime_EventEntityManagerAddEntity) OnEntityManagerAddEntity(entityManager runtime.EntityManager, entity ec.Entity) {
	W.WOnEntityManagerAddEntity(entityManager, entity)
}

// _git_golaxy_org_core_runtime_EventEntityManagerEntityAddComponents is an interface wrapper for EventEntityManagerEntityAddComponents type
type _git_golaxy_org_core_runtime_EventEntityManagerEntityAddComponents struct {
	IValue                              interface{}
	WOnEntityManagerEntityAddComponents func(entityManager runtime.EntityManager, entity ec.Entity, components []ec.Component)
}

func (W _git_golaxy_org_core_runtime_EventEntityManagerEntityAddComponents) OnEntityManagerEntityAddComponents(entityManager runtime.EntityManager, entity ec.Entity, components []ec.Component) {
	W.WOnEntityManagerEntityAddComponents(entityManager, entity, components)
}

// _git_golaxy_org_core_runtime_EventEntityManagerEntityComponentEnableChanged is an interface wrapper for EventEntityManagerEntityComponentEnableChanged type
type _git_golaxy_org_core_runtime_EventEntityManagerEntityComponentEnableChanged struct {
	IValue                                       interface{}
	WOnEntityManagerEntityComponentEnableChanged func(entityManager runtime.EntityManager, entity ec.Entity, component ec.Component, enable bool)
}

func (W _git_golaxy_org_core_runtime_EventEntityManagerEntityComponentEnableChanged) OnEntityManagerEntityComponentEnableChanged(entityManager runtime.EntityManager, entity ec.Entity, component ec.Component, enable bool) {
	W.WOnEntityManagerEntityComponentEnableChanged(entityManager, entity, component, enable)
}

// _git_golaxy_org_core_runtime_EventEntityManagerEntityFirstTouchComponent is an interface wrapper for EventEntityManagerEntityFirstTouchComponent type
type _git_golaxy_org_core_runtime_EventEntityManagerEntityFirstTouchComponent struct {
	IValue                                    interface{}
	WOnEntityManagerEntityFirstTouchComponent func(entityManager runtime.EntityManager, entity ec.Entity, component ec.Component)
}

func (W _git_golaxy_org_core_runtime_EventEntityManagerEntityFirstTouchComponent) OnEntityManagerEntityFirstTouchComponent(entityManager runtime.EntityManager, entity ec.Entity, component ec.Component) {
	W.WOnEntityManagerEntityFirstTouchComponent(entityManager, entity, component)
}

// _git_golaxy_org_core_runtime_EventEntityManagerEntityRemoveComponent is an interface wrapper for EventEntityManagerEntityRemoveComponent type
type _git_golaxy_org_core_runtime_EventEntityManagerEntityRemoveComponent struct {
	IValue                                interface{}
	WOnEntityManagerEntityRemoveComponent func(entityManager runtime.EntityManager, entity ec.Entity, component ec.Component)
}

func (W _git_golaxy_org_core_runtime_EventEntityManagerEntityRemoveComponent) OnEntityManagerEntityRemoveComponent(entityManager runtime.EntityManager, entity ec.Entity, component ec.Component) {
	W.WOnEntityManagerEntityRemoveComponent(entityManager, entity, component)
}

// _git_golaxy_org_core_runtime_EventEntityManagerRemoveEntity is an interface wrapper for EventEntityManagerRemoveEntity type
type _git_golaxy_org_core_runtime_EventEntityManagerRemoveEntity struct {
	IValue                       interface{}
	WOnEntityManagerRemoveEntity func(entityManager runtime.EntityManager, entity ec.Entity)
}

func (W _git_golaxy_org_core_runtime_EventEntityManagerRemoveEntity) OnEntityManagerRemoveEntity(entityManager runtime.EntityManager, entity ec.Entity) {
	W.WOnEntityManagerRemoveEntity(entityManager, entity)
}

// _git_golaxy_org_core_runtime_EventEntityTreeAddNode is an interface wrapper for EventEntityTreeAddNode type
type _git_golaxy_org_core_runtime_EventEntityTreeAddNode struct {
	IValue               interface{}
	WOnEntityTreeAddNode func(entityTree runtime.EntityTree, parentID uid.ID, childID uid.ID)
}

func (W _git_golaxy_org_core_runtime_EventEntityTreeAddNode) OnEntityTreeAddNode(entityTree runtime.EntityTree, parentID uid.ID, childID uid.ID) {
	W.WOnEntityTreeAddNode(entityTree, parentID, childID)
}

// _git_golaxy_org_core_runtime_EventEntityTreeMoveNode is an interface wrapper for EventEntityTreeMoveNode type
type _git_golaxy_org_core_runtime_EventEntityTreeMoveNode struct {
	IValue                interface{}
	WOnEntityTreeMoveNode func(entityTree runtime.EntityTree, childID uid.ID, fromParentID uid.ID, toParentID uid.ID)
}

func (W _git_golaxy_org_core_runtime_EventEntityTreeMoveNode) OnEntityTreeMoveNode(entityTree runtime.EntityTree, childID uid.ID, fromParentID uid.ID, toParentID uid.ID) {
	W.WOnEntityTreeMoveNode(entityTree, childID, fromParentID, toParentID)
}

// _git_golaxy_org_core_runtime_EventEntityTreeRemoveNode is an interface wrapper for EventEntityTreeRemoveNode type
type _git_golaxy_org_core_runtime_EventEntityTreeRemoveNode struct {
	IValue                  interface{}
	WOnEntityTreeRemoveNode func(entityTree runtime.EntityTree, parentID uid.ID, childID uid.ID)
}

func (W _git_golaxy_org_core_runtime_EventEntityTreeRemoveNode) OnEntityTreeRemoveNode(entityTree runtime.EntityTree, parentID uid.ID, childID uid.ID) {
	W.WOnEntityTreeRemoveNode(entityTree, parentID, childID)
}

// _git_golaxy_org_core_runtime_EventInstallAddIn is an interface wrapper for EventInstallAddIn type
type _git_golaxy_org_core_runtime_EventInstallAddIn struct {
	IValue          interface{}
	WOnInstallAddIn func(status runtime.AddInStatus)
}

func (W _git_golaxy_org_core_runtime_EventInstallAddIn) OnInstallAddIn(status runtime.AddInStatus) {
	W.WOnInstallAddIn(status)
}

// _git_golaxy_org_core_runtime_EventUninstallAddIn is an interface wrapper for EventUninstallAddIn type
type _git_golaxy_org_core_runtime_EventUninstallAddIn struct {
	IValue            interface{}
	WOnUninstallAddIn func(status runtime.AddInStatus)
}

func (W _git_golaxy_org_core_runtime_EventUninstallAddIn) OnUninstallAddIn(status runtime.AddInStatus) {
	W.WOnUninstallAddIn(status)
}

// _git_golaxy_org_core_runtime_Frame is an interface wrapper for Frame type
type _git_golaxy_org_core_runtime_Frame struct {
	IValue                interface{}
	WCurFPS               func() float64
	WCurFrames            func() int64
	WLastLoopElapseTime   func() time.Duration
	WLastUpdateElapseTime func() time.Duration
	WLoopBeginTime        func() time.Time
	WRunningBeginTime     func() time.Time
	WRunningElapseTime    func() time.Duration
	WTargetFPS            func() float64
	WTotalFrames          func() int64
	WUpdateBeginTime      func() time.Time
}

func (W _git_golaxy_org_core_runtime_Frame) CurFPS() float64  { return W.WCurFPS() }
func (W _git_golaxy_org_core_runtime_Frame) CurFrames() int64 { return W.WCurFrames() }
func (W _git_golaxy_org_core_runtime_Frame) LastLoopElapseTime() time.Duration {
	return W.WLastLoopElapseTime()
}
func (W _git_golaxy_org_core_runtime_Frame) LastUpdateElapseTime() time.Duration {
	return W.WLastUpdateElapseTime()
}
func (W _git_golaxy_org_core_runtime_Frame) LoopBeginTime() time.Time { return W.WLoopBeginTime() }
func (W _git_golaxy_org_core_runtime_Frame) RunningBeginTime() time.Time {
	return W.WRunningBeginTime()
}
func (W _git_golaxy_org_core_runtime_Frame) RunningElapseTime() time.Duration {
	return W.WRunningElapseTime()
}
func (W _git_golaxy_org_core_runtime_Frame) TargetFPS() float64         { return W.WTargetFPS() }
func (W _git_golaxy_org_core_runtime_Frame) TotalFrames() int64         { return W.WTotalFrames() }
func (W _git_golaxy_org_core_runtime_Frame) UpdateBeginTime() time.Time { return W.WUpdateBeginTime() }

// _git_golaxy_org_core_runtime_GC is an interface wrapper for GC type
type _git_golaxy_org_core_runtime_GC struct {
	IValue  interface{}
	WGC     func()
	WNeedGC func() bool
}

func (W _git_golaxy_org_core_runtime_GC) GC()          { W.WGC() }
func (W _git_golaxy_org_core_runtime_GC) NeedGC() bool { return W.WNeedGC() }

// _git_golaxy_org_core_runtime_GCCollector is an interface wrapper for GCCollector type
type _git_golaxy_org_core_runtime_GCCollector struct {
	IValue     interface{}
	WCollectGC func(gc runtime.GC)
}

func (W _git_golaxy_org_core_runtime_GCCollector) CollectGC(gc runtime.GC) { W.WCollectGC(gc) }

// _git_golaxy_org_core_runtime_IAddInManagerEventTab is an interface wrapper for IAddInManagerEventTab type
type _git_golaxy_org_core_runtime_IAddInManagerEventTab struct {
	IValue                  interface{}
	WEventAddInStateChanged func() event.IEvent
	WEventInstallAddIn      func() event.IEvent
	WEventUninstallAddIn    func() event.IEvent
}

func (W _git_golaxy_org_core_runtime_IAddInManagerEventTab) EventAddInStateChanged() event.IEvent {
	return W.WEventAddInStateChanged()
}
func (W _git_golaxy_org_core_runtime_IAddInManagerEventTab) EventInstallAddIn() event.IEvent {
	return W.WEventInstallAddIn()
}
func (W _git_golaxy_org_core_runtime_IAddInManagerEventTab) EventUninstallAddIn() event.IEvent {
	return W.WEventUninstallAddIn()
}

// _git_golaxy_org_core_runtime_IContextRunningEventTab is an interface wrapper for IContextRunningEventTab type
type _git_golaxy_org_core_runtime_IContextRunningEventTab struct {
	IValue                    interface{}
	WEventContextRunningEvent func() event.IEvent
}

func (W _git_golaxy_org_core_runtime_IContextRunningEventTab) EventContextRunningEvent() event.IEvent {
	return W.WEventContextRunningEvent()
}

// _git_golaxy_org_core_runtime_IEntityManagerEventTab is an interface wrapper for IEntityManagerEventTab type
type _git_golaxy_org_core_runtime_IEntityManagerEventTab struct {
	IValue                                          interface{}
	WEventEntityManagerAddEntity                    func() event.IEvent
	WEventEntityManagerEntityAddComponents          func() event.IEvent
	WEventEntityManagerEntityComponentEnableChanged func() event.IEvent
	WEventEntityManagerEntityFirstTouchComponent    func() event.IEvent
	WEventEntityManagerEntityRemoveComponent        func() event.IEvent
	WEventEntityManagerRemoveEntity                 func() event.IEvent
}

func (W _git_golaxy_org_core_runtime_IEntityManagerEventTab) EventEntityManagerAddEntity() event.IEvent {
	return W.WEventEntityManagerAddEntity()
}
func (W _git_golaxy_org_core_runtime_IEntityManagerEventTab) EventEntityManagerEntityAddComponents() event.IEvent {
	return W.WEventEntityManagerEntityAddComponents()
}
func (W _git_golaxy_org_core_runtime_IEntityManagerEventTab) EventEntityManagerEntityComponentEnableChanged() event.IEvent {
	return W.WEventEntityManagerEntityComponentEnableChanged()
}
func (W _git_golaxy_org_core_runtime_IEntityManagerEventTab) EventEntityManagerEntityFirstTouchComponent() event.IEvent {
	return W.WEventEntityManagerEntityFirstTouchComponent()
}
func (W _git_golaxy_org_core_runtime_IEntityManagerEventTab) EventEntityManagerEntityRemoveComponent() event.IEvent {
	return W.WEventEntityManagerEntityRemoveComponent()
}
func (W _git_golaxy_org_core_runtime_IEntityManagerEventTab) EventEntityManagerRemoveEntity() event.IEvent {
	return W.WEventEntityManagerRemoveEntity()
}

// _git_golaxy_org_core_runtime_IEntityTreeEventTab is an interface wrapper for IEntityTreeEventTab type
type _git_golaxy_org_core_runtime_IEntityTreeEventTab struct {
	IValue                     interface{}
	WEventEntityTreeAddNode    func() event.IEvent
	WEventEntityTreeMoveNode   func() event.IEvent
	WEventEntityTreeRemoveNode func() event.IEvent
}

func (W _git_golaxy_org_core_runtime_IEntityTreeEventTab) EventEntityTreeAddNode() event.IEvent {
	return W.WEventEntityTreeAddNode()
}
func (W _git_golaxy_org_core_runtime_IEntityTreeEventTab) EventEntityTreeMoveNode() event.IEvent {
	return W.WEventEntityTreeMoveNode()
}
func (W _git_golaxy_org_core_runtime_IEntityTreeEventTab) EventEntityTreeRemoveNode() event.IEvent {
	return W.WEventEntityTreeRemoveNode()
}
