// Code generated by 'yaegi extract git.golaxy.org/framework/addins/router'. DO NOT EDIT.

package fwlib

import (
	"context"
	"git.golaxy.org/core/ec"
	"git.golaxy.org/core/utils/async"
	"git.golaxy.org/core/utils/uid"
	"git.golaxy.org/framework/addins/gate"
	"git.golaxy.org/framework/addins/router"
	"git.golaxy.org/framework/net/gtp/transport"
	"reflect"
	"time"
)

func init() {
	Symbols["git.golaxy.org/framework/addins/router/router"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddIn":              reflect.ValueOf(&router.AddIn).Elem(),
		"ErrEntityNotFound":  reflect.ValueOf(&router.ErrEntityNotFound).Elem(),
		"ErrGroupExists":     reflect.ValueOf(&router.ErrGroupExists).Elem(),
		"ErrSessionNotFound": reflect.ValueOf(&router.ErrSessionNotFound).Elem(),
		"With":               reflect.ValueOf(&router.With).Elem(),

		// type definitions
		"IDataIO":       reflect.ValueOf((*router.IDataIO)(nil)),
		"IEventIO":      reflect.ValueOf((*router.IEventIO)(nil)),
		"IGroup":        reflect.ValueOf((*router.IGroup)(nil)),
		"IMapping":      reflect.ValueOf((*router.IMapping)(nil)),
		"IRouter":       reflect.ValueOf((*router.IRouter)(nil)),
		"RouterOptions": reflect.ValueOf((*router.RouterOptions)(nil)),

		// interface wrapper definitions
		"_IDataIO":  reflect.ValueOf((*_git_golaxy_org_framework_addins_router_IDataIO)(nil)),
		"_IEventIO": reflect.ValueOf((*_git_golaxy_org_framework_addins_router_IEventIO)(nil)),
		"_IGroup":   reflect.ValueOf((*_git_golaxy_org_framework_addins_router_IGroup)(nil)),
		"_IMapping": reflect.ValueOf((*_git_golaxy_org_framework_addins_router_IMapping)(nil)),
		"_IRouter":  reflect.ValueOf((*_git_golaxy_org_framework_addins_router_IRouter)(nil)),
	}
}

// _git_golaxy_org_framework_addins_router_IDataIO is an interface wrapper for IDataIO type
type _git_golaxy_org_framework_addins_router_IDataIO struct {
	IValue interface{}
	WSend  func(data []byte) error
}

func (W _git_golaxy_org_framework_addins_router_IDataIO) Send(data []byte) error {
	return W.WSend(data)
}

// _git_golaxy_org_framework_addins_router_IEventIO is an interface wrapper for IEventIO type
type _git_golaxy_org_framework_addins_router_IEventIO struct {
	IValue interface{}
	WSend  func(event transport.IEvent) error
}

func (W _git_golaxy_org_framework_addins_router_IEventIO) Send(event transport.IEvent) error {
	return W.WSend(event)
}

// _git_golaxy_org_framework_addins_router_IGroup is an interface wrapper for IGroup type
type _git_golaxy_org_framework_addins_router_IGroup struct {
	IValue               interface{}
	WAdd                 func(ctx context.Context, ids []uid.Id) error
	WClientAddr          func() string
	WDataIO              func() router.IDataIO
	WDeleted             func() async.Future
	WEventIO             func() router.IEventIO
	WKeepAliveContinuous func(ctx context.Context) (async.Future, error)
	WKeepAliveOnce       func(ctx context.Context) error
	WList                func() []uid.Id
	WName                func() string
	WRemove              func(ctx context.Context, ids []uid.Id) error
}

func (W _git_golaxy_org_framework_addins_router_IGroup) Add(ctx context.Context, ids []uid.Id) error {
	return W.WAdd(ctx, ids)
}
func (W _git_golaxy_org_framework_addins_router_IGroup) ClientAddr() string     { return W.WClientAddr() }
func (W _git_golaxy_org_framework_addins_router_IGroup) DataIO() router.IDataIO { return W.WDataIO() }
func (W _git_golaxy_org_framework_addins_router_IGroup) Deleted() async.Future  { return W.WDeleted() }
func (W _git_golaxy_org_framework_addins_router_IGroup) EventIO() router.IEventIO {
	return W.WEventIO()
}
func (W _git_golaxy_org_framework_addins_router_IGroup) KeepAliveContinuous(ctx context.Context) (async.Future, error) {
	return W.WKeepAliveContinuous(ctx)
}
func (W _git_golaxy_org_framework_addins_router_IGroup) KeepAliveOnce(ctx context.Context) error {
	return W.WKeepAliveOnce(ctx)
}
func (W _git_golaxy_org_framework_addins_router_IGroup) List() []uid.Id { return W.WList() }
func (W _git_golaxy_org_framework_addins_router_IGroup) Name() string   { return W.WName() }
func (W _git_golaxy_org_framework_addins_router_IGroup) Remove(ctx context.Context, ids []uid.Id) error {
	return W.WRemove(ctx, ids)
}

// _git_golaxy_org_framework_addins_router_IMapping is an interface wrapper for IMapping type
type _git_golaxy_org_framework_addins_router_IMapping struct {
	IValue      interface{}
	WClientAddr func() string
	WEntity     func() ec.ConcurrentEntity
	WSession    func() gate.ISession
	WUnmap      func()
	WUnmapped   func() async.Future
}

func (W _git_golaxy_org_framework_addins_router_IMapping) ClientAddr() string { return W.WClientAddr() }
func (W _git_golaxy_org_framework_addins_router_IMapping) Entity() ec.ConcurrentEntity {
	return W.WEntity()
}
func (W _git_golaxy_org_framework_addins_router_IMapping) Session() gate.ISession {
	return W.WSession()
}
func (W _git_golaxy_org_framework_addins_router_IMapping) Unmap() { W.WUnmap() }
func (W _git_golaxy_org_framework_addins_router_IMapping) Unmapped() async.Future {
	return W.WUnmapped()
}

// _git_golaxy_org_framework_addins_router_IRouter is an interface wrapper for IRouter type
type _git_golaxy_org_framework_addins_router_IRouter struct {
	IValue          interface{}
	WAddGroup       func(ctx context.Context, name string, ids []uid.Id, ttl time.Duration) (router.IGroup, error)
	WDeleteGroup    func(ctx context.Context, name string)
	WGetGroupByAddr func(ctx context.Context, addr string) (router.IGroup, bool)
	WGetGroupByName func(ctx context.Context, name string) (router.IGroup, bool)
	WLookup         func(id uid.Id) (router.IMapping, bool)
	WMap            func(entityId uid.Id, sessionId uid.Id) (router.IMapping, error)
}

func (W _git_golaxy_org_framework_addins_router_IRouter) AddGroup(ctx context.Context, name string, ids []uid.Id, ttl time.Duration) (router.IGroup, error) {
	return W.WAddGroup(ctx, name, ids, ttl)
}
func (W _git_golaxy_org_framework_addins_router_IRouter) DeleteGroup(ctx context.Context, name string) {
	W.WDeleteGroup(ctx, name)
}
func (W _git_golaxy_org_framework_addins_router_IRouter) GetGroupByAddr(ctx context.Context, addr string) (router.IGroup, bool) {
	return W.WGetGroupByAddr(ctx, addr)
}
func (W _git_golaxy_org_framework_addins_router_IRouter) GetGroupByName(ctx context.Context, name string) (router.IGroup, bool) {
	return W.WGetGroupByName(ctx, name)
}
func (W _git_golaxy_org_framework_addins_router_IRouter) Lookup(id uid.Id) (router.IMapping, bool) {
	return W.WLookup(id)
}
func (W _git_golaxy_org_framework_addins_router_IRouter) Map(entityId uid.Id, sessionId uid.Id) (router.IMapping, error) {
	return W.WMap(entityId, sessionId)
}
