// Code generated by 'yaegi extract git.golaxy.org/framework/utils/concurrent'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/framework/utils/concurrent"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/framework/utils/concurrent/concurrent"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ErrFutureControllerClosed": reflect.ValueOf(&concurrent.ErrFutureControllerClosed).Elem(),
		"ErrFutureExceeded":         reflect.ValueOf(&concurrent.ErrFutureExceeded).Elem(),
		"NewFutureController":       reflect.ValueOf(concurrent.NewFutureController),

		// type definitions
		"FutureController": reflect.ValueOf((*concurrent.FutureController)(nil)),
		"FutureHandle":     reflect.ValueOf((*concurrent.FutureHandle)(nil)),
	}
}
