// Code generated by 'yaegi extract git.golaxy.org/framework/addins/gate'. DO NOT EDIT.

package fwlib

import (
	"context"
	"git.golaxy.org/core/utils/async"
	"git.golaxy.org/core/utils/uid"
	"git.golaxy.org/framework/addins/gate"
	"git.golaxy.org/framework/net/gtp/transport"
	"reflect"
	"time"
)

func init() {
	Symbols["git.golaxy.org/framework/addins/gate/gate"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddIn":                              reflect.ValueOf(&gate.AddIn).Elem(),
		"ClientDetails":                      reflect.ValueOf(&gate.ClientDetails).Elem(),
		"DefaultWebSocketLocalAddrResolver":  reflect.ValueOf(gate.DefaultWebSocketLocalAddrResolver),
		"DefaultWebSocketRemoteAddrResolver": reflect.ValueOf(gate.DefaultWebSocketRemoteAddrResolver),
		"SessionState_Active":                reflect.ValueOf(gate.SessionState_Active),
		"SessionState_Birth":                 reflect.ValueOf(gate.SessionState_Birth),
		"SessionState_Confirmed":             reflect.ValueOf(gate.SessionState_Confirmed),
		"SessionState_Death":                 reflect.ValueOf(gate.SessionState_Death),
		"SessionState_Inactive":              reflect.ValueOf(gate.SessionState_Inactive),
		"With":                               reflect.ValueOf(&gate.With).Elem(),

		// type definitions
		"Authenticator":             reflect.ValueOf((*gate.Authenticator)(nil)),
		"GateOptions":               reflect.ValueOf((*gate.GateOptions)(nil)),
		"IDataIO":                   reflect.ValueOf((*gate.IDataIO)(nil)),
		"IEventIO":                  reflect.ValueOf((*gate.IEventIO)(nil)),
		"IGate":                     reflect.ValueOf((*gate.IGate)(nil)),
		"ISession":                  reflect.ValueOf((*gate.ISession)(nil)),
		"NetAddr":                   reflect.ValueOf((*gate.NetAddr)(nil)),
		"SessionDataHandler":        reflect.ValueOf((*gate.SessionDataHandler)(nil)),
		"SessionEstablishedHandler": reflect.ValueOf((*gate.SessionEstablishedHandler)(nil)),
		"SessionEventHandler":       reflect.ValueOf((*gate.SessionEventHandler)(nil)),
		"SessionState":              reflect.ValueOf((*gate.SessionState)(nil)),
		"WebSocketAddrResolver":     reflect.ValueOf((*gate.WebSocketAddrResolver)(nil)),

		// interface wrapper definitions
		"_IDataIO":  reflect.ValueOf((*_git_golaxy_org_framework_addins_gate_IDataIO)(nil)),
		"_IEventIO": reflect.ValueOf((*_git_golaxy_org_framework_addins_gate_IEventIO)(nil)),
		"_IGate":    reflect.ValueOf((*_git_golaxy_org_framework_addins_gate_IGate)(nil)),
		"_ISession": reflect.ValueOf((*_git_golaxy_org_framework_addins_gate_ISession)(nil)),
	}
}

// _git_golaxy_org_framework_addins_gate_IDataIO is an interface wrapper for IDataIO type
type _git_golaxy_org_framework_addins_gate_IDataIO struct {
	IValue  interface{}
	WListen func(ctx context.Context, handler gate.SessionDataHandler) error
	WSend   func(data []byte) error
}

func (W _git_golaxy_org_framework_addins_gate_IDataIO) Listen(ctx context.Context, handler gate.SessionDataHandler) error {
	return W.WListen(ctx, handler)
}
func (W _git_golaxy_org_framework_addins_gate_IDataIO) Send(data []byte) error { return W.WSend(data) }

// _git_golaxy_org_framework_addins_gate_IEventIO is an interface wrapper for IEventIO type
type _git_golaxy_org_framework_addins_gate_IEventIO struct {
	IValue  interface{}
	WListen func(ctx context.Context, handler gate.SessionEventHandler) error
	WSend   func(event transport.IEvent) error
}

func (W _git_golaxy_org_framework_addins_gate_IEventIO) Listen(ctx context.Context, handler gate.SessionEventHandler) error {
	return W.WListen(ctx, handler)
}
func (W _git_golaxy_org_framework_addins_gate_IEventIO) Send(event transport.IEvent) error {
	return W.WSend(event)
}

// _git_golaxy_org_framework_addins_gate_IGate is an interface wrapper for IGate type
type _git_golaxy_org_framework_addins_gate_IGate struct {
	IValue interface{}
	WCount func() int64
	WGet   func(id uid.Id) (gate.ISession, bool)
	WWatch func(ctx context.Context, handler gate.SessionEstablishedHandler) (async.Future, error)
}

func (W _git_golaxy_org_framework_addins_gate_IGate) Count() int64 { return W.WCount() }
func (W _git_golaxy_org_framework_addins_gate_IGate) Get(id uid.Id) (gate.ISession, bool) {
	return W.WGet(id)
}
func (W _git_golaxy_org_framework_addins_gate_IGate) Watch(ctx context.Context, handler gate.SessionEstablishedHandler) (async.Future, error) {
	return W.WWatch(ctx, handler)
}

// _git_golaxy_org_framework_addins_gate_ISession is an interface wrapper for ISession type
type _git_golaxy_org_framework_addins_gate_ISession struct {
	IValue      interface{}
	WClose      func(err error) async.Future
	WClosed     func() async.Future
	WDataIO     func() gate.IDataIO
	WDeadline   func() (deadline time.Time, ok bool)
	WDone       func() <-chan struct{}
	WErr        func() error
	WEventIO    func() gate.IEventIO
	WExtensions func() []byte
	WId         func() uid.Id
	WMigrations func() int64
	WNetAddr    func() gate.NetAddr
	WState      func() gate.SessionState
	WString     func() string
	WToken      func() string
	WUserId     func() string
	WValue      func(key any) any
}

func (W _git_golaxy_org_framework_addins_gate_ISession) Close(err error) async.Future {
	return W.WClose(err)
}
func (W _git_golaxy_org_framework_addins_gate_ISession) Closed() async.Future { return W.WClosed() }
func (W _git_golaxy_org_framework_addins_gate_ISession) DataIO() gate.IDataIO { return W.WDataIO() }
func (W _git_golaxy_org_framework_addins_gate_ISession) Deadline() (deadline time.Time, ok bool) {
	return W.WDeadline()
}
func (W _git_golaxy_org_framework_addins_gate_ISession) Done() <-chan struct{}    { return W.WDone() }
func (W _git_golaxy_org_framework_addins_gate_ISession) Err() error               { return W.WErr() }
func (W _git_golaxy_org_framework_addins_gate_ISession) EventIO() gate.IEventIO   { return W.WEventIO() }
func (W _git_golaxy_org_framework_addins_gate_ISession) Extensions() []byte       { return W.WExtensions() }
func (W _git_golaxy_org_framework_addins_gate_ISession) Id() uid.Id               { return W.WId() }
func (W _git_golaxy_org_framework_addins_gate_ISession) Migrations() int64        { return W.WMigrations() }
func (W _git_golaxy_org_framework_addins_gate_ISession) NetAddr() gate.NetAddr    { return W.WNetAddr() }
func (W _git_golaxy_org_framework_addins_gate_ISession) State() gate.SessionState { return W.WState() }
func (W _git_golaxy_org_framework_addins_gate_ISession) String() string {
	if W.WString == nil {
		return ""
	}
	return W.WString()
}
func (W _git_golaxy_org_framework_addins_gate_ISession) Token() string     { return W.WToken() }
func (W _git_golaxy_org_framework_addins_gate_ISession) UserId() string    { return W.WUserId() }
func (W _git_golaxy_org_framework_addins_gate_ISession) Value(key any) any { return W.WValue(key) }
