// Code generated by 'yaegi extract git.golaxy.org/core/extension'. DO NOT EDIT.

package fwlib

import (
	"git.golaxy.org/core/extension"
	"git.golaxy.org/core/utils/iface"
	"reflect"
)

func init() {
	Symbols["git.golaxy.org/core/extension/extension"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddInState_Loaded":   reflect.ValueOf(extension.AddInState_Loaded),
		"AddInState_Running":  reflect.ValueOf(extension.AddInState_Running),
		"AddInState_Unloaded": reflect.ValueOf(extension.AddInState_Unloaded),
		"ErrExtension":        reflect.ValueOf(&extension.ErrExtension).Elem(),
		"GenAddInID":          reflect.ValueOf(extension.GenAddInID),
		"GenAddInName":        reflect.ValueOf(extension.GenAddInName),
		"Uninstall":           reflect.ValueOf(extension.Uninstall),

		// type definitions
		"AddInManager":  reflect.ValueOf((*extension.AddInManager)(nil)),
		"AddInProvider": reflect.ValueOf((*extension.AddInProvider)(nil)),
		"AddInState":    reflect.ValueOf((*extension.AddInState)(nil)),
		"AddInStatus":   reflect.ValueOf((*extension.AddInStatus)(nil)),

		// interface wrapper definitions
		"_AddInManager":  reflect.ValueOf((*_git_golaxy_org_core_extension_AddInManager)(nil)),
		"_AddInProvider": reflect.ValueOf((*_git_golaxy_org_core_extension_AddInProvider)(nil)),
		"_AddInStatus":   reflect.ValueOf((*_git_golaxy_org_core_extension_AddInStatus)(nil)),
	}
}

// _git_golaxy_org_core_extension_AddInManager is an interface wrapper for AddInManager type
type _git_golaxy_org_core_extension_AddInManager struct {
	IValue           interface{}
	WAddInManager    func() extension.AddInManager
	WGetStatusByID   func(id uint64) (extension.AddInStatus, bool)
	WGetStatusByName func(name string) (extension.AddInStatus, bool)
	WInstall         func(addInFace iface.FaceAny, name ...string) extension.AddInStatus
	WListStatuses    func() []extension.AddInStatus
	WUninstall       func(name string)
}

func (W _git_golaxy_org_core_extension_AddInManager) AddInManager() extension.AddInManager {
	return W.WAddInManager()
}
func (W _git_golaxy_org_core_extension_AddInManager) GetStatusByID(id uint64) (extension.AddInStatus, bool) {
	return W.WGetStatusByID(id)
}
func (W _git_golaxy_org_core_extension_AddInManager) GetStatusByName(name string) (extension.AddInStatus, bool) {
	return W.WGetStatusByName(name)
}
func (W _git_golaxy_org_core_extension_AddInManager) Install(addInFace iface.FaceAny, name ...string) extension.AddInStatus {
	return W.WInstall(addInFace, name...)
}
func (W _git_golaxy_org_core_extension_AddInManager) ListStatuses() []extension.AddInStatus {
	return W.WListStatuses()
}
func (W _git_golaxy_org_core_extension_AddInManager) Uninstall(name string) { W.WUninstall(name) }

// _git_golaxy_org_core_extension_AddInProvider is an interface wrapper for AddInProvider type
type _git_golaxy_org_core_extension_AddInProvider struct {
	IValue        interface{}
	WAddInManager func() extension.AddInManager
}

func (W _git_golaxy_org_core_extension_AddInProvider) AddInManager() extension.AddInManager {
	return W.WAddInManager()
}

// _git_golaxy_org_core_extension_AddInStatus is an interface wrapper for AddInStatus type
type _git_golaxy_org_core_extension_AddInStatus struct {
	IValue        interface{}
	WID           func() uint64
	WInstanceFace func() iface.FaceAny
	WName         func() string
	WReflected    func() reflect.Value
	WState        func() extension.AddInState
	WString       func() string
}

func (W _git_golaxy_org_core_extension_AddInStatus) ID() uint64 { return W.WID() }
func (W _git_golaxy_org_core_extension_AddInStatus) InstanceFace() iface.FaceAny {
	return W.WInstanceFace()
}
func (W _git_golaxy_org_core_extension_AddInStatus) Name() string                { return W.WName() }
func (W _git_golaxy_org_core_extension_AddInStatus) Reflected() reflect.Value    { return W.WReflected() }
func (W _git_golaxy_org_core_extension_AddInStatus) State() extension.AddInState { return W.WState() }
func (W _git_golaxy_org_core_extension_AddInStatus) String() string {
	if W.WString == nil {
		return ""
	}
	return W.WString()
}
